import {
    type IPackageType,
    withPackageImport,
    withSourceFile
}                        from "@use-pico/generator";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api/IGenerator";

export interface IWithFilterFormParams {
    forms: IWithFilterFormParams.IForm[];
}

export namespace IWithFilterFormParams {
    export interface IForm {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        translation: {
            namespace: string;
        };
        withFilter?: IWithFilter;
        packages: IPackages;
    }

    export interface IWithFilter {
        type: string;
        package: IPackageType;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @pico).
         */
        schema: string;
    }
}

export const withFilterForm: IGenerator<IWithFilterFormParams> = async (
    {
        barrel,
        directory,
        params: {forms}
    }) => {
    forms.forEach((
        {
            name,
            translation,
            packages,
            withFilter
        }) => {
        console.log(`- Generating [withFilterForm] [${name}]`);

        withSourceFile()
            .withImports({
                imports: {
                    "@use-pico/form-client": [
                        "createFormContext",
                    ],
                    [packages.schema]:   [
                        `type I${name}FilterFormSchemaType`,
                    ],
                },
            })
            .withConsts({
                exports: {
                    [`${name}FilterFormStoreContext`]: {
                        body: `
createFormContext<I${name}FilterFormSchemaType>({
    name: "${name}FilterForm",
})
                        `,
                    },
                }
            })
            .saveTo({
                file:   normalize(`${directory}/context/${name}FilterFormStoreContext.tsx`),
                barrel: false,
            });

        withSourceFile()
            .withImports({
                imports: {
                    "@use-pico/form-client": [
                        "createMantineFormContext",
                    ],
                    [packages.schema]:   [
                        `type I${name}FilterFormSchemaType`,
                    ],
                },
            })
            .withConsts({
                exports: {
                    [`${name}MantineFilterFormContext`]: {
                        body: `createMantineFormContext<I${name}FilterFormSchemaType>()`,
                    },
                },
            })
            .saveTo({
                file:   normalize(`${directory}/context/${name}MantineFilterFormContext.tsx`),
                barrel: false,
            });

        withSourceFile()
            .withImports({
                imports: {
                    "@use-pico/form-client": [
                        "type IWithInputProps",
                        "WithInput",
                    ],
                    [packages.schema]:                            [
                        `type I${name}FilterFormSchemaType`,
                    ],
                    "react":                                      [
                        "type FC",
                    ],
                    [`../context/${name}FilterFormStoreContext`]: [
                        `${name}FilterFormStoreContext`,
                    ],
                },
            })
            .withConsts({
                exports: {
                    [`${name}FilterInput`]: {
                        type: `FC<Omit<IWithInputProps<I${name}FilterFormSchemaType>, "FormContext">>`,
                        body: `
props => {
    return <WithInput
        FormContext={${name}FilterFormStoreContext}
        {...props}
    />;
}
                            `,
                    },
                },
            })
            .saveTo({
                file:   normalize(`${directory}/form/${name}FilterInput.tsx`),
                barrel: false,
            });

        withSourceFile()
            .withImports({
                imports: {
                    "@use-pico/filter-client": [
                        "BaseFilterForm",
                        "type IBaseFilterFormProps",
                    ],
                    "react":                                        [
                        "type FC",
                    ],
                    [packages.schema]:                              [
                        `type I${name}FilterFormSchemaType as IFilterFormSchemaType`,
                        `type I${name}SourceSchema as ISourceSchema`,
                    ],
                    [`../context/${name}FilterFormStoreContext`]:   [
                        `${name}FilterFormStoreContext as FilterFormStoreContext`,
                    ],
                    [`../context/${name}MantineFilterFormContext`]: [
                        `${name}MantineFilterFormContext as MantineFilterFormContext`,
                    ],
                    [`../source/${name}Source`]:                    [
                        `${name}Source as Source`,
                    ],
                },
            })
            .withImports({
                imports: {
                    [packages.schema]: [
                        `${name}FilterFormSchema as FilterFormSchema`,
                    ],
                },
            })
            .withImports(withFilter?.package?.withPackage?.package ? {
                imports: {
                    [withFilter.package?.withPackage?.package]: [
                        withFilter?.package.type,
                    ]
                },
            } : undefined)
            .withConsts({
                exports: {
                    [`Base${name}FilterForm`]: {
                        type: `FC<IBase${name}FilterFormProps>`,
                        // language=text
                        body: `
${withFilter ? `({getFilterName, ...props}) => {` : `props => {`}
    return <BaseFilterForm<IFilterFormSchemaType, ISourceSchema>
        Source={Source}
        MantineContext={MantineFilterFormContext}
        schemas={FilterFormSchema}
        FormContext={FilterFormStoreContext}
        withTranslation={{
            namespace: "${translation.namespace}",
            label:     "${name}BaseFilterForm",
        }}${withFilter ? `\n\t\twithFilterQuery={getFilterName ? {getName: getFilterName, type: "${withFilter.type}", Source: ${withPackageImport(withFilter.package)}} : undefined}\n\t\t` : "\n\t\t"}{...props}
    />;
}
                        `,
                    },
                },
            })
            .withInterfaces({
                exports: {
                    [`IBase${name}FilterFormProps`]: {
                        extends: [
                            {
                                type: `Omit<IBaseFilterFormProps<IFilterFormSchemaType, ISourceSchema>, "Source" | "FormContext" | "MantineContext" | "withTranslation">`,
                            },
                        ],
                        body:    `
getFilterName?: IBaseFilterFormProps.IWithFilterQuery<IFilterFormSchemaType>["getName"];
                        `,
                    },
                },
            })
            .saveTo({
                file: normalize(`${directory}/form/Base${name}FilterForm.tsx`),
                barrel,
            });
    });
};
