/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './@routes/__root'
import { Route as LocaleImport } from './@routes/$locale'
import { Route as IndexImport } from './@routes/index'
import { Route as LocaleIndexImport } from './@routes/$locale/index'
import { Route as LocaleAppsDeriveanImport } from './@routes/$locale/apps/derivean'
import { Route as LocaleAppsDeriveanRootImport } from './@routes/$locale/apps/derivean/root'
import { Route as LocaleAppsDeriveanGameImport } from './@routes/$locale/apps/derivean/game'
import { Route as LocaleAppsDeriveanRootIndexImport } from './@routes/$locale/apps/derivean/root/index'
import { Route as LocaleAppsDeriveanGameIndexImport } from './@routes/$locale/apps/derivean/game/index'
import { Route as LocaleAppsDeriveanRootEditorImport } from './@routes/$locale/apps/derivean/root/editor'
import { Route as LocaleAppsDeriveanPublicRegisterImport } from './@routes/$locale/apps/derivean/public/register'
import { Route as LocaleAppsDeriveanPublicLogoutImport } from './@routes/$locale/apps/derivean/public/logout'
import { Route as LocaleAppsDeriveanPublicLoginImport } from './@routes/$locale/apps/derivean/public/login'
import { Route as LocaleAppsDeriveanGameManagementImport } from './@routes/$locale/apps/derivean/game/management'
import { Route as LocaleAppsDeriveanDbSchemaImport } from './@routes/$locale/apps/derivean/db/schema'
import { Route as LocaleAppsDeriveanGameManagementIndexImport } from './@routes/$locale/apps/derivean/game/management/index'
import { Route as LocaleAppsDeriveanRootUserListImport } from './@routes/$locale/apps/derivean/root/user/list'
import { Route as LocaleAppsDeriveanRootUserIdImport } from './@routes/$locale/apps/derivean/root/user/$id'
import { Route as LocaleAppsDeriveanRootTagListImport } from './@routes/$locale/apps/derivean/root/tag/list'
import { Route as LocaleAppsDeriveanRootResourceListImport } from './@routes/$locale/apps/derivean/root/resource/list'
import { Route as LocaleAppsDeriveanRootResourceIdImport } from './@routes/$locale/apps/derivean/root/resource/$id'
import { Route as LocaleAppsDeriveanRootDefaultInventoryImport } from './@routes/$locale/apps/derivean/root/default/inventory'
import { Route as LocaleAppsDeriveanRootBlueprintListImport } from './@routes/$locale/apps/derivean/root/blueprint/list'
import { Route as LocaleAppsDeriveanRootBlueprintIdImport } from './@routes/$locale/apps/derivean/root/blueprint/$id'
import { Route as LocaleAppsDeriveanGameManagementInventoryImport } from './@routes/$locale/apps/derivean/game/management/inventory'
import { Route as LocaleAppsDeriveanRootUserIdViewImport } from './@routes/$locale/apps/derivean/root/user/$id/view'
import { Route as LocaleAppsDeriveanRootUserIdInventoryImport } from './@routes/$locale/apps/derivean/root/user/$id/inventory'
import { Route as LocaleAppsDeriveanRootResourceIdViewImport } from './@routes/$locale/apps/derivean/root/resource/$id/view'
import { Route as LocaleAppsDeriveanRootBlueprintProductionIdImport } from './@routes/$locale/apps/derivean/root/blueprint/production/$id'
import { Route as LocaleAppsDeriveanRootBlueprintIdViewImport } from './@routes/$locale/apps/derivean/root/blueprint/$id/view'
import { Route as LocaleAppsDeriveanRootBlueprintIdRequirementsImport } from './@routes/$locale/apps/derivean/root/blueprint/$id/requirements'
import { Route as LocaleAppsDeriveanRootBlueprintIdProductionImport } from './@routes/$locale/apps/derivean/root/blueprint/$id/production'
import { Route as LocaleAppsDeriveanRootBlueprintIdEditImport } from './@routes/$locale/apps/derivean/root/blueprint/$id/edit'
import { Route as LocaleAppsDeriveanRootBlueprintIdDependenciesImport } from './@routes/$locale/apps/derivean/root/blueprint/$id/dependencies'
import { Route as LocaleAppsDeriveanRootBlueprintIdConflictsImport } from './@routes/$locale/apps/derivean/root/blueprint/$id/conflicts'
import { Route as LocaleAppsDeriveanGameManagementProductionQueueImport } from './@routes/$locale/apps/derivean/game/management/production/queue'
import { Route as LocaleAppsDeriveanGameManagementBlueprintListImport } from './@routes/$locale/apps/derivean/game/management/blueprint/list'
import { Route as LocaleAppsDeriveanGameManagementBlueprintIdImport } from './@routes/$locale/apps/derivean/game/management/blueprint/$id'
import { Route as LocaleAppsDeriveanRootUserIdBuildingListImport } from './@routes/$locale/apps/derivean/root/user/$id/building/list'
import { Route as LocaleAppsDeriveanRootBlueprintProductionIdResourcesImport } from './@routes/$locale/apps/derivean/root/blueprint/production/$id/resources'
import { Route as LocaleAppsDeriveanRootBlueprintProductionIdRequirementsImport } from './@routes/$locale/apps/derivean/root/blueprint/production/$id/requirements'
import { Route as LocaleAppsDeriveanRootBlueprintProductionIdDependenciesImport } from './@routes/$locale/apps/derivean/root/blueprint/production/$id/dependencies'
import { Route as LocaleAppsDeriveanGameManagementBlueprintProductionIdImport } from './@routes/$locale/apps/derivean/game/management/blueprint/production/$id'
import { Route as LocaleAppsDeriveanGameManagementBlueprintIdViewImport } from './@routes/$locale/apps/derivean/game/management/blueprint/$id/view'
import { Route as LocaleAppsDeriveanGameManagementBlueprintIdRequirementsImport } from './@routes/$locale/apps/derivean/game/management/blueprint/$id/requirements'
import { Route as LocaleAppsDeriveanGameManagementBlueprintIdProductionImport } from './@routes/$locale/apps/derivean/game/management/blueprint/$id/production'
import { Route as LocaleAppsDeriveanGameManagementBlueprintIdDependenciesImport } from './@routes/$locale/apps/derivean/game/management/blueprint/$id/dependencies'
import { Route as LocaleAppsDeriveanGameManagementBlueprintIdConflictsImport } from './@routes/$locale/apps/derivean/game/management/blueprint/$id/conflicts'
import { Route as LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesImport } from './@routes/$locale/apps/derivean/game/management/blueprint/production/$id/resources'
import { Route as LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsImport } from './@routes/$locale/apps/derivean/game/management/blueprint/production/$id/requirements'
import { Route as LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesImport } from './@routes/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies'

// Create/Update Routes

const LocaleRoute = LocaleImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleIndexRoute = LocaleIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleAppsDeriveanRoute = LocaleAppsDeriveanImport.update({
  id: '/apps/derivean',
  path: '/apps/derivean',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleAppsDeriveanRootRoute = LocaleAppsDeriveanRootImport.update({
  id: '/root',
  path: '/root',
  getParentRoute: () => LocaleAppsDeriveanRoute,
} as any)

const LocaleAppsDeriveanGameRoute = LocaleAppsDeriveanGameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => LocaleAppsDeriveanRoute,
} as any)

const LocaleAppsDeriveanRootIndexRoute =
  LocaleAppsDeriveanRootIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanGameIndexRoute =
  LocaleAppsDeriveanGameIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAppsDeriveanGameRoute,
  } as any)

const LocaleAppsDeriveanRootEditorRoute =
  LocaleAppsDeriveanRootEditorImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanPublicRegisterRoute =
  LocaleAppsDeriveanPublicRegisterImport.update({
    id: '/public/register',
    path: '/public/register',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any)

const LocaleAppsDeriveanPublicLogoutRoute =
  LocaleAppsDeriveanPublicLogoutImport.update({
    id: '/public/logout',
    path: '/public/logout',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any)

const LocaleAppsDeriveanPublicLoginRoute =
  LocaleAppsDeriveanPublicLoginImport.update({
    id: '/public/login',
    path: '/public/login',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any)

const LocaleAppsDeriveanGameManagementRoute =
  LocaleAppsDeriveanGameManagementImport.update({
    id: '/management',
    path: '/management',
    getParentRoute: () => LocaleAppsDeriveanGameRoute,
  } as any)

const LocaleAppsDeriveanDbSchemaRoute = LocaleAppsDeriveanDbSchemaImport.update(
  {
    id: '/db/schema',
    path: '/db/schema',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any,
)

const LocaleAppsDeriveanGameManagementIndexRoute =
  LocaleAppsDeriveanGameManagementIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAppsDeriveanGameManagementRoute,
  } as any)

const LocaleAppsDeriveanRootUserListRoute =
  LocaleAppsDeriveanRootUserListImport.update({
    id: '/user/list',
    path: '/user/list',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdRoute =
  LocaleAppsDeriveanRootUserIdImport.update({
    id: '/user/$id',
    path: '/user/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootTagListRoute =
  LocaleAppsDeriveanRootTagListImport.update({
    id: '/tag/list',
    path: '/tag/list',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootResourceListRoute =
  LocaleAppsDeriveanRootResourceListImport.update({
    id: '/resource/list',
    path: '/resource/list',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootResourceIdRoute =
  LocaleAppsDeriveanRootResourceIdImport.update({
    id: '/resource/$id',
    path: '/resource/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootDefaultInventoryRoute =
  LocaleAppsDeriveanRootDefaultInventoryImport.update({
    id: '/default/inventory',
    path: '/default/inventory',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintListRoute =
  LocaleAppsDeriveanRootBlueprintListImport.update({
    id: '/blueprint/list',
    path: '/blueprint/list',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdRoute =
  LocaleAppsDeriveanRootBlueprintIdImport.update({
    id: '/blueprint/$id',
    path: '/blueprint/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanGameManagementInventoryRoute =
  LocaleAppsDeriveanGameManagementInventoryImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => LocaleAppsDeriveanGameManagementRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdViewRoute =
  LocaleAppsDeriveanRootUserIdViewImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => LocaleAppsDeriveanRootUserIdRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdInventoryRoute =
  LocaleAppsDeriveanRootUserIdInventoryImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => LocaleAppsDeriveanRootUserIdRoute,
  } as any)

const LocaleAppsDeriveanRootResourceIdViewRoute =
  LocaleAppsDeriveanRootResourceIdViewImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => LocaleAppsDeriveanRootResourceIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintProductionIdRoute =
  LocaleAppsDeriveanRootBlueprintProductionIdImport.update({
    id: '/blueprint/production/$id',
    path: '/blueprint/production/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdViewRoute =
  LocaleAppsDeriveanRootBlueprintIdViewImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdRequirementsRoute =
  LocaleAppsDeriveanRootBlueprintIdRequirementsImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdProductionRoute =
  LocaleAppsDeriveanRootBlueprintIdProductionImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdEditRoute =
  LocaleAppsDeriveanRootBlueprintIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdDependenciesRoute =
  LocaleAppsDeriveanRootBlueprintIdDependenciesImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintIdConflictsRoute =
  LocaleAppsDeriveanRootBlueprintIdConflictsImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementProductionQueueRoute =
  LocaleAppsDeriveanGameManagementProductionQueueImport.update({
    id: '/production/queue',
    path: '/production/queue',
    getParentRoute: () => LocaleAppsDeriveanGameManagementRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintListRoute =
  LocaleAppsDeriveanGameManagementBlueprintListImport.update({
    id: '/blueprint/list',
    path: '/blueprint/list',
    getParentRoute: () => LocaleAppsDeriveanGameManagementRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintIdRoute =
  LocaleAppsDeriveanGameManagementBlueprintIdImport.update({
    id: '/blueprint/$id',
    path: '/blueprint/$id',
    getParentRoute: () => LocaleAppsDeriveanGameManagementRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdBuildingListRoute =
  LocaleAppsDeriveanRootUserIdBuildingListImport.update({
    id: '/building/list',
    path: '/building/list',
    getParentRoute: () => LocaleAppsDeriveanRootUserIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute =
  LocaleAppsDeriveanRootBlueprintProductionIdResourcesImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintProductionIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute =
  LocaleAppsDeriveanRootBlueprintProductionIdRequirementsImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintProductionIdRoute,
  } as any)

const LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute =
  LocaleAppsDeriveanRootBlueprintProductionIdDependenciesImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => LocaleAppsDeriveanRootBlueprintProductionIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute =
  LocaleAppsDeriveanGameManagementBlueprintProductionIdImport.update({
    id: '/blueprint/production/$id',
    path: '/blueprint/production/$id',
    getParentRoute: () => LocaleAppsDeriveanGameManagementRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintIdViewRoute =
  LocaleAppsDeriveanGameManagementBlueprintIdViewImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => LocaleAppsDeriveanGameManagementBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute =
  LocaleAppsDeriveanGameManagementBlueprintIdRequirementsImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => LocaleAppsDeriveanGameManagementBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute =
  LocaleAppsDeriveanGameManagementBlueprintIdProductionImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => LocaleAppsDeriveanGameManagementBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute =
  LocaleAppsDeriveanGameManagementBlueprintIdDependenciesImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => LocaleAppsDeriveanGameManagementBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute =
  LocaleAppsDeriveanGameManagementBlueprintIdConflictsImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => LocaleAppsDeriveanGameManagementBlueprintIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute =
  LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () =>
      LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute,
  } as any)

const LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute =
  LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsImport.update(
    {
      id: '/requirements',
      path: '/requirements',
      getParentRoute: () =>
        LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute,
    } as any,
  )

const LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute =
  LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesImport.update(
    {
      id: '/dependencies',
      path: '/dependencies',
      getParentRoute: () =>
        LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/derivean': {
      id: '/$locale/apps/derivean'
      path: '/apps/derivean'
      fullPath: '/$locale/apps/derivean'
      preLoaderRoute: typeof LocaleAppsDeriveanImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/derivean/game': {
      id: '/$locale/apps/derivean/game'
      path: '/game'
      fullPath: '/$locale/apps/derivean/game'
      preLoaderRoute: typeof LocaleAppsDeriveanGameImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/root': {
      id: '/$locale/apps/derivean/root'
      path: '/root'
      fullPath: '/$locale/apps/derivean/root'
      preLoaderRoute: typeof LocaleAppsDeriveanRootImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/db/schema': {
      id: '/$locale/apps/derivean/db/schema'
      path: '/db/schema'
      fullPath: '/$locale/apps/derivean/db/schema'
      preLoaderRoute: typeof LocaleAppsDeriveanDbSchemaImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/game/management': {
      id: '/$locale/apps/derivean/game/management'
      path: '/management'
      fullPath: '/$locale/apps/derivean/game/management'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementImport
      parentRoute: typeof LocaleAppsDeriveanGameImport
    }
    '/$locale/apps/derivean/public/login': {
      id: '/$locale/apps/derivean/public/login'
      path: '/public/login'
      fullPath: '/$locale/apps/derivean/public/login'
      preLoaderRoute: typeof LocaleAppsDeriveanPublicLoginImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/public/logout': {
      id: '/$locale/apps/derivean/public/logout'
      path: '/public/logout'
      fullPath: '/$locale/apps/derivean/public/logout'
      preLoaderRoute: typeof LocaleAppsDeriveanPublicLogoutImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/public/register': {
      id: '/$locale/apps/derivean/public/register'
      path: '/public/register'
      fullPath: '/$locale/apps/derivean/public/register'
      preLoaderRoute: typeof LocaleAppsDeriveanPublicRegisterImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/root/editor': {
      id: '/$locale/apps/derivean/root/editor'
      path: '/editor'
      fullPath: '/$locale/apps/derivean/root/editor'
      preLoaderRoute: typeof LocaleAppsDeriveanRootEditorImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/game/': {
      id: '/$locale/apps/derivean/game/'
      path: '/'
      fullPath: '/$locale/apps/derivean/game/'
      preLoaderRoute: typeof LocaleAppsDeriveanGameIndexImport
      parentRoute: typeof LocaleAppsDeriveanGameImport
    }
    '/$locale/apps/derivean/root/': {
      id: '/$locale/apps/derivean/root/'
      path: '/'
      fullPath: '/$locale/apps/derivean/root/'
      preLoaderRoute: typeof LocaleAppsDeriveanRootIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/game/management/inventory': {
      id: '/$locale/apps/derivean/game/management/inventory'
      path: '/inventory'
      fullPath: '/$locale/apps/derivean/game/management/inventory'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementInventoryImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementImport
    }
    '/$locale/apps/derivean/root/blueprint/$id': {
      id: '/$locale/apps/derivean/root/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/blueprint/list': {
      id: '/$locale/apps/derivean/root/blueprint/list'
      path: '/blueprint/list'
      fullPath: '/$locale/apps/derivean/root/blueprint/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintListImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/default/inventory': {
      id: '/$locale/apps/derivean/root/default/inventory'
      path: '/default/inventory'
      fullPath: '/$locale/apps/derivean/root/default/inventory'
      preLoaderRoute: typeof LocaleAppsDeriveanRootDefaultInventoryImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/resource/$id': {
      id: '/$locale/apps/derivean/root/resource/$id'
      path: '/resource/$id'
      fullPath: '/$locale/apps/derivean/root/resource/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootResourceIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/resource/list': {
      id: '/$locale/apps/derivean/root/resource/list'
      path: '/resource/list'
      fullPath: '/$locale/apps/derivean/root/resource/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootResourceListImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/tag/list': {
      id: '/$locale/apps/derivean/root/tag/list'
      path: '/tag/list'
      fullPath: '/$locale/apps/derivean/root/tag/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootTagListImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/user/$id': {
      id: '/$locale/apps/derivean/root/user/$id'
      path: '/user/$id'
      fullPath: '/$locale/apps/derivean/root/user/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/user/list': {
      id: '/$locale/apps/derivean/root/user/list'
      path: '/user/list'
      fullPath: '/$locale/apps/derivean/root/user/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserListImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/game/management/': {
      id: '/$locale/apps/derivean/game/management/'
      path: '/'
      fullPath: '/$locale/apps/derivean/game/management/'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementIndexImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementImport
    }
    '/$locale/apps/derivean/game/management/blueprint/$id': {
      id: '/$locale/apps/derivean/game/management/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementImport
    }
    '/$locale/apps/derivean/game/management/blueprint/list': {
      id: '/$locale/apps/derivean/game/management/blueprint/list'
      path: '/blueprint/list'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/list'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintListImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementImport
    }
    '/$locale/apps/derivean/game/management/production/queue': {
      id: '/$locale/apps/derivean/game/management/production/queue'
      path: '/production/queue'
      fullPath: '/$locale/apps/derivean/game/management/production/queue'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementProductionQueueImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementImport
    }
    '/$locale/apps/derivean/root/blueprint/$id/conflicts': {
      id: '/$locale/apps/derivean/root/blueprint/$id/conflicts'
      path: '/conflicts'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id/conflicts'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdConflictsImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
    }
    '/$locale/apps/derivean/root/blueprint/$id/dependencies': {
      id: '/$locale/apps/derivean/root/blueprint/$id/dependencies'
      path: '/dependencies'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id/dependencies'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdDependenciesImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
    }
    '/$locale/apps/derivean/root/blueprint/$id/edit': {
      id: '/$locale/apps/derivean/root/blueprint/$id/edit'
      path: '/edit'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id/edit'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdEditImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
    }
    '/$locale/apps/derivean/root/blueprint/$id/production': {
      id: '/$locale/apps/derivean/root/blueprint/$id/production'
      path: '/production'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id/production'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdProductionImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
    }
    '/$locale/apps/derivean/root/blueprint/$id/requirements': {
      id: '/$locale/apps/derivean/root/blueprint/$id/requirements'
      path: '/requirements'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id/requirements'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdRequirementsImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
    }
    '/$locale/apps/derivean/root/blueprint/$id/view': {
      id: '/$locale/apps/derivean/root/blueprint/$id/view'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/blueprint/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintIdViewImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintIdImport
    }
    '/$locale/apps/derivean/root/blueprint/production/$id': {
      id: '/$locale/apps/derivean/root/blueprint/production/$id'
      path: '/blueprint/production/$id'
      fullPath: '/$locale/apps/derivean/root/blueprint/production/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/resource/$id/view': {
      id: '/$locale/apps/derivean/root/resource/$id/view'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/resource/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootResourceIdViewImport
      parentRoute: typeof LocaleAppsDeriveanRootResourceIdImport
    }
    '/$locale/apps/derivean/root/user/$id/inventory': {
      id: '/$locale/apps/derivean/root/user/$id/inventory'
      path: '/inventory'
      fullPath: '/$locale/apps/derivean/root/user/$id/inventory'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdInventoryImport
      parentRoute: typeof LocaleAppsDeriveanRootUserIdImport
    }
    '/$locale/apps/derivean/root/user/$id/view': {
      id: '/$locale/apps/derivean/root/user/$id/view'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/user/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdViewImport
      parentRoute: typeof LocaleAppsDeriveanRootUserIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/$id/conflicts': {
      id: '/$locale/apps/derivean/game/management/blueprint/$id/conflicts'
      path: '/conflicts'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/$id/conflicts'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdConflictsImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/$id/dependencies': {
      id: '/$locale/apps/derivean/game/management/blueprint/$id/dependencies'
      path: '/dependencies'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/$id/dependencies'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdDependenciesImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/$id/production': {
      id: '/$locale/apps/derivean/game/management/blueprint/$id/production'
      path: '/production'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/$id/production'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdProductionImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/$id/requirements': {
      id: '/$locale/apps/derivean/game/management/blueprint/$id/requirements'
      path: '/requirements'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/$id/requirements'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdRequirementsImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/$id/view': {
      id: '/$locale/apps/derivean/game/management/blueprint/$id/view'
      path: '/view'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdViewImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/production/$id': {
      id: '/$locale/apps/derivean/game/management/blueprint/production/$id'
      path: '/blueprint/production/$id'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/production/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementImport
    }
    '/$locale/apps/derivean/root/blueprint/production/$id/dependencies': {
      id: '/$locale/apps/derivean/root/blueprint/production/$id/dependencies'
      path: '/dependencies'
      fullPath: '/$locale/apps/derivean/root/blueprint/production/$id/dependencies'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdDependenciesImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdImport
    }
    '/$locale/apps/derivean/root/blueprint/production/$id/requirements': {
      id: '/$locale/apps/derivean/root/blueprint/production/$id/requirements'
      path: '/requirements'
      fullPath: '/$locale/apps/derivean/root/blueprint/production/$id/requirements'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdRequirementsImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdImport
    }
    '/$locale/apps/derivean/root/blueprint/production/$id/resources': {
      id: '/$locale/apps/derivean/root/blueprint/production/$id/resources'
      path: '/resources'
      fullPath: '/$locale/apps/derivean/root/blueprint/production/$id/resources'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdResourcesImport
      parentRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdImport
    }
    '/$locale/apps/derivean/root/user/$id/building/list': {
      id: '/$locale/apps/derivean/root/user/$id/building/list'
      path: '/building/list'
      fullPath: '/$locale/apps/derivean/root/user/$id/building/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdBuildingListImport
      parentRoute: typeof LocaleAppsDeriveanRootUserIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies': {
      id: '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies'
      path: '/dependencies'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements': {
      id: '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements'
      path: '/requirements'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdImport
    }
    '/$locale/apps/derivean/game/management/blueprint/production/$id/resources': {
      id: '/$locale/apps/derivean/game/management/blueprint/production/$id/resources'
      path: '/resources'
      fullPath: '/$locale/apps/derivean/game/management/blueprint/production/$id/resources'
      preLoaderRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesImport
      parentRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdImport
    }
  }
}

// Create and export the route tree

interface LocaleAppsDeriveanGameManagementBlueprintIdRouteChildren {
  LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute
  LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute
  LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute
  LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute
  LocaleAppsDeriveanGameManagementBlueprintIdViewRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdViewRoute
}

const LocaleAppsDeriveanGameManagementBlueprintIdRouteChildren: LocaleAppsDeriveanGameManagementBlueprintIdRouteChildren =
  {
    LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute:
      LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute,
    LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute:
      LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute,
    LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute:
      LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute,
    LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute:
      LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute,
    LocaleAppsDeriveanGameManagementBlueprintIdViewRoute:
      LocaleAppsDeriveanGameManagementBlueprintIdViewRoute,
  }

const LocaleAppsDeriveanGameManagementBlueprintIdRouteWithChildren =
  LocaleAppsDeriveanGameManagementBlueprintIdRoute._addFileChildren(
    LocaleAppsDeriveanGameManagementBlueprintIdRouteChildren,
  )

interface LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteChildren {
  LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute
  LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute
  LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute
}

const LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteChildren: LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteChildren =
  {
    LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute:
      LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute,
    LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute:
      LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute,
    LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute:
      LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute,
  }

const LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteWithChildren =
  LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute._addFileChildren(
    LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteChildren,
  )

interface LocaleAppsDeriveanGameManagementRouteChildren {
  LocaleAppsDeriveanGameManagementInventoryRoute: typeof LocaleAppsDeriveanGameManagementInventoryRoute
  LocaleAppsDeriveanGameManagementIndexRoute: typeof LocaleAppsDeriveanGameManagementIndexRoute
  LocaleAppsDeriveanGameManagementBlueprintIdRoute: typeof LocaleAppsDeriveanGameManagementBlueprintIdRouteWithChildren
  LocaleAppsDeriveanGameManagementBlueprintListRoute: typeof LocaleAppsDeriveanGameManagementBlueprintListRoute
  LocaleAppsDeriveanGameManagementProductionQueueRoute: typeof LocaleAppsDeriveanGameManagementProductionQueueRoute
  LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute: typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteWithChildren
}

const LocaleAppsDeriveanGameManagementRouteChildren: LocaleAppsDeriveanGameManagementRouteChildren =
  {
    LocaleAppsDeriveanGameManagementInventoryRoute:
      LocaleAppsDeriveanGameManagementInventoryRoute,
    LocaleAppsDeriveanGameManagementIndexRoute:
      LocaleAppsDeriveanGameManagementIndexRoute,
    LocaleAppsDeriveanGameManagementBlueprintIdRoute:
      LocaleAppsDeriveanGameManagementBlueprintIdRouteWithChildren,
    LocaleAppsDeriveanGameManagementBlueprintListRoute:
      LocaleAppsDeriveanGameManagementBlueprintListRoute,
    LocaleAppsDeriveanGameManagementProductionQueueRoute:
      LocaleAppsDeriveanGameManagementProductionQueueRoute,
    LocaleAppsDeriveanGameManagementBlueprintProductionIdRoute:
      LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteWithChildren,
  }

const LocaleAppsDeriveanGameManagementRouteWithChildren =
  LocaleAppsDeriveanGameManagementRoute._addFileChildren(
    LocaleAppsDeriveanGameManagementRouteChildren,
  )

interface LocaleAppsDeriveanGameRouteChildren {
  LocaleAppsDeriveanGameManagementRoute: typeof LocaleAppsDeriveanGameManagementRouteWithChildren
  LocaleAppsDeriveanGameIndexRoute: typeof LocaleAppsDeriveanGameIndexRoute
}

const LocaleAppsDeriveanGameRouteChildren: LocaleAppsDeriveanGameRouteChildren =
  {
    LocaleAppsDeriveanGameManagementRoute:
      LocaleAppsDeriveanGameManagementRouteWithChildren,
    LocaleAppsDeriveanGameIndexRoute: LocaleAppsDeriveanGameIndexRoute,
  }

const LocaleAppsDeriveanGameRouteWithChildren =
  LocaleAppsDeriveanGameRoute._addFileChildren(
    LocaleAppsDeriveanGameRouteChildren,
  )

interface LocaleAppsDeriveanRootBlueprintIdRouteChildren {
  LocaleAppsDeriveanRootBlueprintIdConflictsRoute: typeof LocaleAppsDeriveanRootBlueprintIdConflictsRoute
  LocaleAppsDeriveanRootBlueprintIdDependenciesRoute: typeof LocaleAppsDeriveanRootBlueprintIdDependenciesRoute
  LocaleAppsDeriveanRootBlueprintIdEditRoute: typeof LocaleAppsDeriveanRootBlueprintIdEditRoute
  LocaleAppsDeriveanRootBlueprintIdProductionRoute: typeof LocaleAppsDeriveanRootBlueprintIdProductionRoute
  LocaleAppsDeriveanRootBlueprintIdRequirementsRoute: typeof LocaleAppsDeriveanRootBlueprintIdRequirementsRoute
  LocaleAppsDeriveanRootBlueprintIdViewRoute: typeof LocaleAppsDeriveanRootBlueprintIdViewRoute
}

const LocaleAppsDeriveanRootBlueprintIdRouteChildren: LocaleAppsDeriveanRootBlueprintIdRouteChildren =
  {
    LocaleAppsDeriveanRootBlueprintIdConflictsRoute:
      LocaleAppsDeriveanRootBlueprintIdConflictsRoute,
    LocaleAppsDeriveanRootBlueprintIdDependenciesRoute:
      LocaleAppsDeriveanRootBlueprintIdDependenciesRoute,
    LocaleAppsDeriveanRootBlueprintIdEditRoute:
      LocaleAppsDeriveanRootBlueprintIdEditRoute,
    LocaleAppsDeriveanRootBlueprintIdProductionRoute:
      LocaleAppsDeriveanRootBlueprintIdProductionRoute,
    LocaleAppsDeriveanRootBlueprintIdRequirementsRoute:
      LocaleAppsDeriveanRootBlueprintIdRequirementsRoute,
    LocaleAppsDeriveanRootBlueprintIdViewRoute:
      LocaleAppsDeriveanRootBlueprintIdViewRoute,
  }

const LocaleAppsDeriveanRootBlueprintIdRouteWithChildren =
  LocaleAppsDeriveanRootBlueprintIdRoute._addFileChildren(
    LocaleAppsDeriveanRootBlueprintIdRouteChildren,
  )

interface LocaleAppsDeriveanRootResourceIdRouteChildren {
  LocaleAppsDeriveanRootResourceIdViewRoute: typeof LocaleAppsDeriveanRootResourceIdViewRoute
}

const LocaleAppsDeriveanRootResourceIdRouteChildren: LocaleAppsDeriveanRootResourceIdRouteChildren =
  {
    LocaleAppsDeriveanRootResourceIdViewRoute:
      LocaleAppsDeriveanRootResourceIdViewRoute,
  }

const LocaleAppsDeriveanRootResourceIdRouteWithChildren =
  LocaleAppsDeriveanRootResourceIdRoute._addFileChildren(
    LocaleAppsDeriveanRootResourceIdRouteChildren,
  )

interface LocaleAppsDeriveanRootUserIdRouteChildren {
  LocaleAppsDeriveanRootUserIdInventoryRoute: typeof LocaleAppsDeriveanRootUserIdInventoryRoute
  LocaleAppsDeriveanRootUserIdViewRoute: typeof LocaleAppsDeriveanRootUserIdViewRoute
  LocaleAppsDeriveanRootUserIdBuildingListRoute: typeof LocaleAppsDeriveanRootUserIdBuildingListRoute
}

const LocaleAppsDeriveanRootUserIdRouteChildren: LocaleAppsDeriveanRootUserIdRouteChildren =
  {
    LocaleAppsDeriveanRootUserIdInventoryRoute:
      LocaleAppsDeriveanRootUserIdInventoryRoute,
    LocaleAppsDeriveanRootUserIdViewRoute:
      LocaleAppsDeriveanRootUserIdViewRoute,
    LocaleAppsDeriveanRootUserIdBuildingListRoute:
      LocaleAppsDeriveanRootUserIdBuildingListRoute,
  }

const LocaleAppsDeriveanRootUserIdRouteWithChildren =
  LocaleAppsDeriveanRootUserIdRoute._addFileChildren(
    LocaleAppsDeriveanRootUserIdRouteChildren,
  )

interface LocaleAppsDeriveanRootBlueprintProductionIdRouteChildren {
  LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute
  LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute
  LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute
}

const LocaleAppsDeriveanRootBlueprintProductionIdRouteChildren: LocaleAppsDeriveanRootBlueprintProductionIdRouteChildren =
  {
    LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute:
      LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute,
    LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute:
      LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute,
    LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute:
      LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute,
  }

const LocaleAppsDeriveanRootBlueprintProductionIdRouteWithChildren =
  LocaleAppsDeriveanRootBlueprintProductionIdRoute._addFileChildren(
    LocaleAppsDeriveanRootBlueprintProductionIdRouteChildren,
  )

interface LocaleAppsDeriveanRootRouteChildren {
  LocaleAppsDeriveanRootEditorRoute: typeof LocaleAppsDeriveanRootEditorRoute
  LocaleAppsDeriveanRootIndexRoute: typeof LocaleAppsDeriveanRootIndexRoute
  LocaleAppsDeriveanRootBlueprintIdRoute: typeof LocaleAppsDeriveanRootBlueprintIdRouteWithChildren
  LocaleAppsDeriveanRootBlueprintListRoute: typeof LocaleAppsDeriveanRootBlueprintListRoute
  LocaleAppsDeriveanRootDefaultInventoryRoute: typeof LocaleAppsDeriveanRootDefaultInventoryRoute
  LocaleAppsDeriveanRootResourceIdRoute: typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  LocaleAppsDeriveanRootResourceListRoute: typeof LocaleAppsDeriveanRootResourceListRoute
  LocaleAppsDeriveanRootTagListRoute: typeof LocaleAppsDeriveanRootTagListRoute
  LocaleAppsDeriveanRootUserIdRoute: typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  LocaleAppsDeriveanRootUserListRoute: typeof LocaleAppsDeriveanRootUserListRoute
  LocaleAppsDeriveanRootBlueprintProductionIdRoute: typeof LocaleAppsDeriveanRootBlueprintProductionIdRouteWithChildren
}

const LocaleAppsDeriveanRootRouteChildren: LocaleAppsDeriveanRootRouteChildren =
  {
    LocaleAppsDeriveanRootEditorRoute: LocaleAppsDeriveanRootEditorRoute,
    LocaleAppsDeriveanRootIndexRoute: LocaleAppsDeriveanRootIndexRoute,
    LocaleAppsDeriveanRootBlueprintIdRoute:
      LocaleAppsDeriveanRootBlueprintIdRouteWithChildren,
    LocaleAppsDeriveanRootBlueprintListRoute:
      LocaleAppsDeriveanRootBlueprintListRoute,
    LocaleAppsDeriveanRootDefaultInventoryRoute:
      LocaleAppsDeriveanRootDefaultInventoryRoute,
    LocaleAppsDeriveanRootResourceIdRoute:
      LocaleAppsDeriveanRootResourceIdRouteWithChildren,
    LocaleAppsDeriveanRootResourceListRoute:
      LocaleAppsDeriveanRootResourceListRoute,
    LocaleAppsDeriveanRootTagListRoute: LocaleAppsDeriveanRootTagListRoute,
    LocaleAppsDeriveanRootUserIdRoute:
      LocaleAppsDeriveanRootUserIdRouteWithChildren,
    LocaleAppsDeriveanRootUserListRoute: LocaleAppsDeriveanRootUserListRoute,
    LocaleAppsDeriveanRootBlueprintProductionIdRoute:
      LocaleAppsDeriveanRootBlueprintProductionIdRouteWithChildren,
  }

const LocaleAppsDeriveanRootRouteWithChildren =
  LocaleAppsDeriveanRootRoute._addFileChildren(
    LocaleAppsDeriveanRootRouteChildren,
  )

interface LocaleAppsDeriveanRouteChildren {
  LocaleAppsDeriveanGameRoute: typeof LocaleAppsDeriveanGameRouteWithChildren
  LocaleAppsDeriveanRootRoute: typeof LocaleAppsDeriveanRootRouteWithChildren
  LocaleAppsDeriveanDbSchemaRoute: typeof LocaleAppsDeriveanDbSchemaRoute
  LocaleAppsDeriveanPublicLoginRoute: typeof LocaleAppsDeriveanPublicLoginRoute
  LocaleAppsDeriveanPublicLogoutRoute: typeof LocaleAppsDeriveanPublicLogoutRoute
  LocaleAppsDeriveanPublicRegisterRoute: typeof LocaleAppsDeriveanPublicRegisterRoute
}

const LocaleAppsDeriveanRouteChildren: LocaleAppsDeriveanRouteChildren = {
  LocaleAppsDeriveanGameRoute: LocaleAppsDeriveanGameRouteWithChildren,
  LocaleAppsDeriveanRootRoute: LocaleAppsDeriveanRootRouteWithChildren,
  LocaleAppsDeriveanDbSchemaRoute: LocaleAppsDeriveanDbSchemaRoute,
  LocaleAppsDeriveanPublicLoginRoute: LocaleAppsDeriveanPublicLoginRoute,
  LocaleAppsDeriveanPublicLogoutRoute: LocaleAppsDeriveanPublicLogoutRoute,
  LocaleAppsDeriveanPublicRegisterRoute: LocaleAppsDeriveanPublicRegisterRoute,
}

const LocaleAppsDeriveanRouteWithChildren =
  LocaleAppsDeriveanRoute._addFileChildren(LocaleAppsDeriveanRouteChildren)

interface LocaleRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAppsDeriveanRoute: typeof LocaleAppsDeriveanRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAppsDeriveanRoute: LocaleAppsDeriveanRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanRouteWithChildren
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean/db/schema': typeof LocaleAppsDeriveanDbSchemaRoute
  '/$locale/apps/derivean/game/management': typeof LocaleAppsDeriveanGameManagementRouteWithChildren
  '/$locale/apps/derivean/public/login': typeof LocaleAppsDeriveanPublicLoginRoute
  '/$locale/apps/derivean/public/logout': typeof LocaleAppsDeriveanPublicLogoutRoute
  '/$locale/apps/derivean/public/register': typeof LocaleAppsDeriveanPublicRegisterRoute
  '/$locale/apps/derivean/root/editor': typeof LocaleAppsDeriveanRootEditorRoute
  '/$locale/apps/derivean/game/': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/': typeof LocaleAppsDeriveanRootIndexRoute
  '/$locale/apps/derivean/game/management/inventory': typeof LocaleAppsDeriveanGameManagementInventoryRoute
  '/$locale/apps/derivean/root/blueprint/$id': typeof LocaleAppsDeriveanRootBlueprintIdRouteWithChildren
  '/$locale/apps/derivean/root/blueprint/list': typeof LocaleAppsDeriveanRootBlueprintListRoute
  '/$locale/apps/derivean/root/default/inventory': typeof LocaleAppsDeriveanRootDefaultInventoryRoute
  '/$locale/apps/derivean/root/resource/$id': typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/list': typeof LocaleAppsDeriveanRootResourceListRoute
  '/$locale/apps/derivean/root/tag/list': typeof LocaleAppsDeriveanRootTagListRoute
  '/$locale/apps/derivean/root/user/$id': typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  '/$locale/apps/derivean/root/user/list': typeof LocaleAppsDeriveanRootUserListRoute
  '/$locale/apps/derivean/game/management/': typeof LocaleAppsDeriveanGameManagementIndexRoute
  '/$locale/apps/derivean/game/management/blueprint/$id': typeof LocaleAppsDeriveanGameManagementBlueprintIdRouteWithChildren
  '/$locale/apps/derivean/game/management/blueprint/list': typeof LocaleAppsDeriveanGameManagementBlueprintListRoute
  '/$locale/apps/derivean/game/management/production/queue': typeof LocaleAppsDeriveanGameManagementProductionQueueRoute
  '/$locale/apps/derivean/root/blueprint/$id/conflicts': typeof LocaleAppsDeriveanRootBlueprintIdConflictsRoute
  '/$locale/apps/derivean/root/blueprint/$id/dependencies': typeof LocaleAppsDeriveanRootBlueprintIdDependenciesRoute
  '/$locale/apps/derivean/root/blueprint/$id/edit': typeof LocaleAppsDeriveanRootBlueprintIdEditRoute
  '/$locale/apps/derivean/root/blueprint/$id/production': typeof LocaleAppsDeriveanRootBlueprintIdProductionRoute
  '/$locale/apps/derivean/root/blueprint/$id/requirements': typeof LocaleAppsDeriveanRootBlueprintIdRequirementsRoute
  '/$locale/apps/derivean/root/blueprint/$id/view': typeof LocaleAppsDeriveanRootBlueprintIdViewRoute
  '/$locale/apps/derivean/root/blueprint/production/$id': typeof LocaleAppsDeriveanRootBlueprintProductionIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/$id/view': typeof LocaleAppsDeriveanRootResourceIdViewRoute
  '/$locale/apps/derivean/root/user/$id/inventory': typeof LocaleAppsDeriveanRootUserIdInventoryRoute
  '/$locale/apps/derivean/root/user/$id/view': typeof LocaleAppsDeriveanRootUserIdViewRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/conflicts': typeof LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/dependencies': typeof LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/production': typeof LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/requirements': typeof LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/view': typeof LocaleAppsDeriveanGameManagementBlueprintIdViewRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteWithChildren
  '/$locale/apps/derivean/root/blueprint/production/$id/dependencies': typeof LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute
  '/$locale/apps/derivean/root/blueprint/production/$id/requirements': typeof LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute
  '/$locale/apps/derivean/root/blueprint/production/$id/resources': typeof LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute
  '/$locale/apps/derivean/root/user/$id/building/list': typeof LocaleAppsDeriveanRootUserIdBuildingListRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/resources': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanRouteWithChildren
  '/$locale/apps/derivean/db/schema': typeof LocaleAppsDeriveanDbSchemaRoute
  '/$locale/apps/derivean/public/login': typeof LocaleAppsDeriveanPublicLoginRoute
  '/$locale/apps/derivean/public/logout': typeof LocaleAppsDeriveanPublicLogoutRoute
  '/$locale/apps/derivean/public/register': typeof LocaleAppsDeriveanPublicRegisterRoute
  '/$locale/apps/derivean/root/editor': typeof LocaleAppsDeriveanRootEditorRoute
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootIndexRoute
  '/$locale/apps/derivean/game/management/inventory': typeof LocaleAppsDeriveanGameManagementInventoryRoute
  '/$locale/apps/derivean/root/blueprint/$id': typeof LocaleAppsDeriveanRootBlueprintIdRouteWithChildren
  '/$locale/apps/derivean/root/blueprint/list': typeof LocaleAppsDeriveanRootBlueprintListRoute
  '/$locale/apps/derivean/root/default/inventory': typeof LocaleAppsDeriveanRootDefaultInventoryRoute
  '/$locale/apps/derivean/root/resource/$id': typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/list': typeof LocaleAppsDeriveanRootResourceListRoute
  '/$locale/apps/derivean/root/tag/list': typeof LocaleAppsDeriveanRootTagListRoute
  '/$locale/apps/derivean/root/user/$id': typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  '/$locale/apps/derivean/root/user/list': typeof LocaleAppsDeriveanRootUserListRoute
  '/$locale/apps/derivean/game/management': typeof LocaleAppsDeriveanGameManagementIndexRoute
  '/$locale/apps/derivean/game/management/blueprint/$id': typeof LocaleAppsDeriveanGameManagementBlueprintIdRouteWithChildren
  '/$locale/apps/derivean/game/management/blueprint/list': typeof LocaleAppsDeriveanGameManagementBlueprintListRoute
  '/$locale/apps/derivean/game/management/production/queue': typeof LocaleAppsDeriveanGameManagementProductionQueueRoute
  '/$locale/apps/derivean/root/blueprint/$id/conflicts': typeof LocaleAppsDeriveanRootBlueprintIdConflictsRoute
  '/$locale/apps/derivean/root/blueprint/$id/dependencies': typeof LocaleAppsDeriveanRootBlueprintIdDependenciesRoute
  '/$locale/apps/derivean/root/blueprint/$id/edit': typeof LocaleAppsDeriveanRootBlueprintIdEditRoute
  '/$locale/apps/derivean/root/blueprint/$id/production': typeof LocaleAppsDeriveanRootBlueprintIdProductionRoute
  '/$locale/apps/derivean/root/blueprint/$id/requirements': typeof LocaleAppsDeriveanRootBlueprintIdRequirementsRoute
  '/$locale/apps/derivean/root/blueprint/$id/view': typeof LocaleAppsDeriveanRootBlueprintIdViewRoute
  '/$locale/apps/derivean/root/blueprint/production/$id': typeof LocaleAppsDeriveanRootBlueprintProductionIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/$id/view': typeof LocaleAppsDeriveanRootResourceIdViewRoute
  '/$locale/apps/derivean/root/user/$id/inventory': typeof LocaleAppsDeriveanRootUserIdInventoryRoute
  '/$locale/apps/derivean/root/user/$id/view': typeof LocaleAppsDeriveanRootUserIdViewRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/conflicts': typeof LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/dependencies': typeof LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/production': typeof LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/requirements': typeof LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/view': typeof LocaleAppsDeriveanGameManagementBlueprintIdViewRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteWithChildren
  '/$locale/apps/derivean/root/blueprint/production/$id/dependencies': typeof LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute
  '/$locale/apps/derivean/root/blueprint/production/$id/requirements': typeof LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute
  '/$locale/apps/derivean/root/blueprint/production/$id/resources': typeof LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute
  '/$locale/apps/derivean/root/user/$id/building/list': typeof LocaleAppsDeriveanRootUserIdBuildingListRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/resources': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanRouteWithChildren
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean/db/schema': typeof LocaleAppsDeriveanDbSchemaRoute
  '/$locale/apps/derivean/game/management': typeof LocaleAppsDeriveanGameManagementRouteWithChildren
  '/$locale/apps/derivean/public/login': typeof LocaleAppsDeriveanPublicLoginRoute
  '/$locale/apps/derivean/public/logout': typeof LocaleAppsDeriveanPublicLogoutRoute
  '/$locale/apps/derivean/public/register': typeof LocaleAppsDeriveanPublicRegisterRoute
  '/$locale/apps/derivean/root/editor': typeof LocaleAppsDeriveanRootEditorRoute
  '/$locale/apps/derivean/game/': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/': typeof LocaleAppsDeriveanRootIndexRoute
  '/$locale/apps/derivean/game/management/inventory': typeof LocaleAppsDeriveanGameManagementInventoryRoute
  '/$locale/apps/derivean/root/blueprint/$id': typeof LocaleAppsDeriveanRootBlueprintIdRouteWithChildren
  '/$locale/apps/derivean/root/blueprint/list': typeof LocaleAppsDeriveanRootBlueprintListRoute
  '/$locale/apps/derivean/root/default/inventory': typeof LocaleAppsDeriveanRootDefaultInventoryRoute
  '/$locale/apps/derivean/root/resource/$id': typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/list': typeof LocaleAppsDeriveanRootResourceListRoute
  '/$locale/apps/derivean/root/tag/list': typeof LocaleAppsDeriveanRootTagListRoute
  '/$locale/apps/derivean/root/user/$id': typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  '/$locale/apps/derivean/root/user/list': typeof LocaleAppsDeriveanRootUserListRoute
  '/$locale/apps/derivean/game/management/': typeof LocaleAppsDeriveanGameManagementIndexRoute
  '/$locale/apps/derivean/game/management/blueprint/$id': typeof LocaleAppsDeriveanGameManagementBlueprintIdRouteWithChildren
  '/$locale/apps/derivean/game/management/blueprint/list': typeof LocaleAppsDeriveanGameManagementBlueprintListRoute
  '/$locale/apps/derivean/game/management/production/queue': typeof LocaleAppsDeriveanGameManagementProductionQueueRoute
  '/$locale/apps/derivean/root/blueprint/$id/conflicts': typeof LocaleAppsDeriveanRootBlueprintIdConflictsRoute
  '/$locale/apps/derivean/root/blueprint/$id/dependencies': typeof LocaleAppsDeriveanRootBlueprintIdDependenciesRoute
  '/$locale/apps/derivean/root/blueprint/$id/edit': typeof LocaleAppsDeriveanRootBlueprintIdEditRoute
  '/$locale/apps/derivean/root/blueprint/$id/production': typeof LocaleAppsDeriveanRootBlueprintIdProductionRoute
  '/$locale/apps/derivean/root/blueprint/$id/requirements': typeof LocaleAppsDeriveanRootBlueprintIdRequirementsRoute
  '/$locale/apps/derivean/root/blueprint/$id/view': typeof LocaleAppsDeriveanRootBlueprintIdViewRoute
  '/$locale/apps/derivean/root/blueprint/production/$id': typeof LocaleAppsDeriveanRootBlueprintProductionIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/$id/view': typeof LocaleAppsDeriveanRootResourceIdViewRoute
  '/$locale/apps/derivean/root/user/$id/inventory': typeof LocaleAppsDeriveanRootUserIdInventoryRoute
  '/$locale/apps/derivean/root/user/$id/view': typeof LocaleAppsDeriveanRootUserIdViewRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/conflicts': typeof LocaleAppsDeriveanGameManagementBlueprintIdConflictsRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/dependencies': typeof LocaleAppsDeriveanGameManagementBlueprintIdDependenciesRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/production': typeof LocaleAppsDeriveanGameManagementBlueprintIdProductionRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/requirements': typeof LocaleAppsDeriveanGameManagementBlueprintIdRequirementsRoute
  '/$locale/apps/derivean/game/management/blueprint/$id/view': typeof LocaleAppsDeriveanGameManagementBlueprintIdViewRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRouteWithChildren
  '/$locale/apps/derivean/root/blueprint/production/$id/dependencies': typeof LocaleAppsDeriveanRootBlueprintProductionIdDependenciesRoute
  '/$locale/apps/derivean/root/blueprint/production/$id/requirements': typeof LocaleAppsDeriveanRootBlueprintProductionIdRequirementsRoute
  '/$locale/apps/derivean/root/blueprint/production/$id/resources': typeof LocaleAppsDeriveanRootBlueprintProductionIdResourcesRoute
  '/$locale/apps/derivean/root/user/$id/building/list': typeof LocaleAppsDeriveanRootUserIdBuildingListRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdDependenciesRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdRequirementsRoute
  '/$locale/apps/derivean/game/management/blueprint/production/$id/resources': typeof LocaleAppsDeriveanGameManagementBlueprintProductionIdResourcesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/apps/derivean'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/db/schema'
    | '/$locale/apps/derivean/game/management'
    | '/$locale/apps/derivean/public/login'
    | '/$locale/apps/derivean/public/logout'
    | '/$locale/apps/derivean/public/register'
    | '/$locale/apps/derivean/root/editor'
    | '/$locale/apps/derivean/game/'
    | '/$locale/apps/derivean/root/'
    | '/$locale/apps/derivean/game/management/inventory'
    | '/$locale/apps/derivean/root/blueprint/$id'
    | '/$locale/apps/derivean/root/blueprint/list'
    | '/$locale/apps/derivean/root/default/inventory'
    | '/$locale/apps/derivean/root/resource/$id'
    | '/$locale/apps/derivean/root/resource/list'
    | '/$locale/apps/derivean/root/tag/list'
    | '/$locale/apps/derivean/root/user/$id'
    | '/$locale/apps/derivean/root/user/list'
    | '/$locale/apps/derivean/game/management/'
    | '/$locale/apps/derivean/game/management/blueprint/$id'
    | '/$locale/apps/derivean/game/management/blueprint/list'
    | '/$locale/apps/derivean/game/management/production/queue'
    | '/$locale/apps/derivean/root/blueprint/$id/conflicts'
    | '/$locale/apps/derivean/root/blueprint/$id/dependencies'
    | '/$locale/apps/derivean/root/blueprint/$id/edit'
    | '/$locale/apps/derivean/root/blueprint/$id/production'
    | '/$locale/apps/derivean/root/blueprint/$id/requirements'
    | '/$locale/apps/derivean/root/blueprint/$id/view'
    | '/$locale/apps/derivean/root/blueprint/production/$id'
    | '/$locale/apps/derivean/root/resource/$id/view'
    | '/$locale/apps/derivean/root/user/$id/inventory'
    | '/$locale/apps/derivean/root/user/$id/view'
    | '/$locale/apps/derivean/game/management/blueprint/$id/conflicts'
    | '/$locale/apps/derivean/game/management/blueprint/$id/dependencies'
    | '/$locale/apps/derivean/game/management/blueprint/$id/production'
    | '/$locale/apps/derivean/game/management/blueprint/$id/requirements'
    | '/$locale/apps/derivean/game/management/blueprint/$id/view'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id'
    | '/$locale/apps/derivean/root/blueprint/production/$id/dependencies'
    | '/$locale/apps/derivean/root/blueprint/production/$id/requirements'
    | '/$locale/apps/derivean/root/blueprint/production/$id/resources'
    | '/$locale/apps/derivean/root/user/$id/building/list'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/apps/derivean'
    | '/$locale/apps/derivean/db/schema'
    | '/$locale/apps/derivean/public/login'
    | '/$locale/apps/derivean/public/logout'
    | '/$locale/apps/derivean/public/register'
    | '/$locale/apps/derivean/root/editor'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/game/management/inventory'
    | '/$locale/apps/derivean/root/blueprint/$id'
    | '/$locale/apps/derivean/root/blueprint/list'
    | '/$locale/apps/derivean/root/default/inventory'
    | '/$locale/apps/derivean/root/resource/$id'
    | '/$locale/apps/derivean/root/resource/list'
    | '/$locale/apps/derivean/root/tag/list'
    | '/$locale/apps/derivean/root/user/$id'
    | '/$locale/apps/derivean/root/user/list'
    | '/$locale/apps/derivean/game/management'
    | '/$locale/apps/derivean/game/management/blueprint/$id'
    | '/$locale/apps/derivean/game/management/blueprint/list'
    | '/$locale/apps/derivean/game/management/production/queue'
    | '/$locale/apps/derivean/root/blueprint/$id/conflicts'
    | '/$locale/apps/derivean/root/blueprint/$id/dependencies'
    | '/$locale/apps/derivean/root/blueprint/$id/edit'
    | '/$locale/apps/derivean/root/blueprint/$id/production'
    | '/$locale/apps/derivean/root/blueprint/$id/requirements'
    | '/$locale/apps/derivean/root/blueprint/$id/view'
    | '/$locale/apps/derivean/root/blueprint/production/$id'
    | '/$locale/apps/derivean/root/resource/$id/view'
    | '/$locale/apps/derivean/root/user/$id/inventory'
    | '/$locale/apps/derivean/root/user/$id/view'
    | '/$locale/apps/derivean/game/management/blueprint/$id/conflicts'
    | '/$locale/apps/derivean/game/management/blueprint/$id/dependencies'
    | '/$locale/apps/derivean/game/management/blueprint/$id/production'
    | '/$locale/apps/derivean/game/management/blueprint/$id/requirements'
    | '/$locale/apps/derivean/game/management/blueprint/$id/view'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id'
    | '/$locale/apps/derivean/root/blueprint/production/$id/dependencies'
    | '/$locale/apps/derivean/root/blueprint/production/$id/requirements'
    | '/$locale/apps/derivean/root/blueprint/production/$id/resources'
    | '/$locale/apps/derivean/root/user/$id/building/list'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/resources'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/apps/derivean'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/db/schema'
    | '/$locale/apps/derivean/game/management'
    | '/$locale/apps/derivean/public/login'
    | '/$locale/apps/derivean/public/logout'
    | '/$locale/apps/derivean/public/register'
    | '/$locale/apps/derivean/root/editor'
    | '/$locale/apps/derivean/game/'
    | '/$locale/apps/derivean/root/'
    | '/$locale/apps/derivean/game/management/inventory'
    | '/$locale/apps/derivean/root/blueprint/$id'
    | '/$locale/apps/derivean/root/blueprint/list'
    | '/$locale/apps/derivean/root/default/inventory'
    | '/$locale/apps/derivean/root/resource/$id'
    | '/$locale/apps/derivean/root/resource/list'
    | '/$locale/apps/derivean/root/tag/list'
    | '/$locale/apps/derivean/root/user/$id'
    | '/$locale/apps/derivean/root/user/list'
    | '/$locale/apps/derivean/game/management/'
    | '/$locale/apps/derivean/game/management/blueprint/$id'
    | '/$locale/apps/derivean/game/management/blueprint/list'
    | '/$locale/apps/derivean/game/management/production/queue'
    | '/$locale/apps/derivean/root/blueprint/$id/conflicts'
    | '/$locale/apps/derivean/root/blueprint/$id/dependencies'
    | '/$locale/apps/derivean/root/blueprint/$id/edit'
    | '/$locale/apps/derivean/root/blueprint/$id/production'
    | '/$locale/apps/derivean/root/blueprint/$id/requirements'
    | '/$locale/apps/derivean/root/blueprint/$id/view'
    | '/$locale/apps/derivean/root/blueprint/production/$id'
    | '/$locale/apps/derivean/root/resource/$id/view'
    | '/$locale/apps/derivean/root/user/$id/inventory'
    | '/$locale/apps/derivean/root/user/$id/view'
    | '/$locale/apps/derivean/game/management/blueprint/$id/conflicts'
    | '/$locale/apps/derivean/game/management/blueprint/$id/dependencies'
    | '/$locale/apps/derivean/game/management/blueprint/$id/production'
    | '/$locale/apps/derivean/game/management/blueprint/$id/requirements'
    | '/$locale/apps/derivean/game/management/blueprint/$id/view'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id'
    | '/$locale/apps/derivean/root/blueprint/production/$id/dependencies'
    | '/$locale/apps/derivean/root/blueprint/production/$id/requirements'
    | '/$locale/apps/derivean/root/blueprint/production/$id/resources'
    | '/$locale/apps/derivean/root/user/$id/building/list'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/requirements'
    | '/$locale/apps/derivean/game/management/blueprint/production/$id/resources'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale": {
      "filePath": "$locale.tsx",
      "children": [
        "/$locale/",
        "/$locale/apps/derivean"
      ]
    },
    "/$locale/": {
      "filePath": "$locale/index.tsx",
      "parent": "/$locale"
    },
    "/$locale/apps/derivean": {
      "filePath": "$locale/apps/derivean.tsx",
      "parent": "/$locale",
      "children": [
        "/$locale/apps/derivean/game",
        "/$locale/apps/derivean/root",
        "/$locale/apps/derivean/db/schema",
        "/$locale/apps/derivean/public/login",
        "/$locale/apps/derivean/public/logout",
        "/$locale/apps/derivean/public/register"
      ]
    },
    "/$locale/apps/derivean/game": {
      "filePath": "$locale/apps/derivean/game.tsx",
      "parent": "/$locale/apps/derivean",
      "children": [
        "/$locale/apps/derivean/game/management",
        "/$locale/apps/derivean/game/"
      ]
    },
    "/$locale/apps/derivean/root": {
      "filePath": "$locale/apps/derivean/root.tsx",
      "parent": "/$locale/apps/derivean",
      "children": [
        "/$locale/apps/derivean/root/editor",
        "/$locale/apps/derivean/root/",
        "/$locale/apps/derivean/root/blueprint/$id",
        "/$locale/apps/derivean/root/blueprint/list",
        "/$locale/apps/derivean/root/default/inventory",
        "/$locale/apps/derivean/root/resource/$id",
        "/$locale/apps/derivean/root/resource/list",
        "/$locale/apps/derivean/root/tag/list",
        "/$locale/apps/derivean/root/user/$id",
        "/$locale/apps/derivean/root/user/list",
        "/$locale/apps/derivean/root/blueprint/production/$id"
      ]
    },
    "/$locale/apps/derivean/db/schema": {
      "filePath": "$locale/apps/derivean/db/schema.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/game/management": {
      "filePath": "$locale/apps/derivean/game/management.tsx",
      "parent": "/$locale/apps/derivean/game",
      "children": [
        "/$locale/apps/derivean/game/management/inventory",
        "/$locale/apps/derivean/game/management/",
        "/$locale/apps/derivean/game/management/blueprint/$id",
        "/$locale/apps/derivean/game/management/blueprint/list",
        "/$locale/apps/derivean/game/management/production/queue",
        "/$locale/apps/derivean/game/management/blueprint/production/$id"
      ]
    },
    "/$locale/apps/derivean/public/login": {
      "filePath": "$locale/apps/derivean/public/login.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/public/logout": {
      "filePath": "$locale/apps/derivean/public/logout.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/public/register": {
      "filePath": "$locale/apps/derivean/public/register.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/root/editor": {
      "filePath": "$locale/apps/derivean/root/editor.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/game/": {
      "filePath": "$locale/apps/derivean/game/index.tsx",
      "parent": "/$locale/apps/derivean/game"
    },
    "/$locale/apps/derivean/root/": {
      "filePath": "$locale/apps/derivean/root/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/game/management/inventory": {
      "filePath": "$locale/apps/derivean/game/management/inventory.tsx",
      "parent": "/$locale/apps/derivean/game/management"
    },
    "/$locale/apps/derivean/root/blueprint/$id": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/blueprint/$id/conflicts",
        "/$locale/apps/derivean/root/blueprint/$id/dependencies",
        "/$locale/apps/derivean/root/blueprint/$id/edit",
        "/$locale/apps/derivean/root/blueprint/$id/production",
        "/$locale/apps/derivean/root/blueprint/$id/requirements",
        "/$locale/apps/derivean/root/blueprint/$id/view"
      ]
    },
    "/$locale/apps/derivean/root/blueprint/list": {
      "filePath": "$locale/apps/derivean/root/blueprint/list.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/default/inventory": {
      "filePath": "$locale/apps/derivean/root/default/inventory.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/resource/$id": {
      "filePath": "$locale/apps/derivean/root/resource/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/resource/$id/view"
      ]
    },
    "/$locale/apps/derivean/root/resource/list": {
      "filePath": "$locale/apps/derivean/root/resource/list.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/tag/list": {
      "filePath": "$locale/apps/derivean/root/tag/list.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/user/$id": {
      "filePath": "$locale/apps/derivean/root/user/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/user/$id/inventory",
        "/$locale/apps/derivean/root/user/$id/view",
        "/$locale/apps/derivean/root/user/$id/building/list"
      ]
    },
    "/$locale/apps/derivean/root/user/list": {
      "filePath": "$locale/apps/derivean/root/user/list.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/game/management/": {
      "filePath": "$locale/apps/derivean/game/management/index.tsx",
      "parent": "/$locale/apps/derivean/game/management"
    },
    "/$locale/apps/derivean/game/management/blueprint/$id": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/$id.tsx",
      "parent": "/$locale/apps/derivean/game/management",
      "children": [
        "/$locale/apps/derivean/game/management/blueprint/$id/conflicts",
        "/$locale/apps/derivean/game/management/blueprint/$id/dependencies",
        "/$locale/apps/derivean/game/management/blueprint/$id/production",
        "/$locale/apps/derivean/game/management/blueprint/$id/requirements",
        "/$locale/apps/derivean/game/management/blueprint/$id/view"
      ]
    },
    "/$locale/apps/derivean/game/management/blueprint/list": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/list.tsx",
      "parent": "/$locale/apps/derivean/game/management"
    },
    "/$locale/apps/derivean/game/management/production/queue": {
      "filePath": "$locale/apps/derivean/game/management/production/queue.tsx",
      "parent": "/$locale/apps/derivean/game/management"
    },
    "/$locale/apps/derivean/root/blueprint/$id/conflicts": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id/conflicts.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/$id"
    },
    "/$locale/apps/derivean/root/blueprint/$id/dependencies": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id/dependencies.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/$id"
    },
    "/$locale/apps/derivean/root/blueprint/$id/edit": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id/edit.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/$id"
    },
    "/$locale/apps/derivean/root/blueprint/$id/production": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id/production.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/$id"
    },
    "/$locale/apps/derivean/root/blueprint/$id/requirements": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id/requirements.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/$id"
    },
    "/$locale/apps/derivean/root/blueprint/$id/view": {
      "filePath": "$locale/apps/derivean/root/blueprint/$id/view.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/$id"
    },
    "/$locale/apps/derivean/root/blueprint/production/$id": {
      "filePath": "$locale/apps/derivean/root/blueprint/production/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/blueprint/production/$id/dependencies",
        "/$locale/apps/derivean/root/blueprint/production/$id/requirements",
        "/$locale/apps/derivean/root/blueprint/production/$id/resources"
      ]
    },
    "/$locale/apps/derivean/root/resource/$id/view": {
      "filePath": "$locale/apps/derivean/root/resource/$id/view.tsx",
      "parent": "/$locale/apps/derivean/root/resource/$id"
    },
    "/$locale/apps/derivean/root/user/$id/inventory": {
      "filePath": "$locale/apps/derivean/root/user/$id/inventory.tsx",
      "parent": "/$locale/apps/derivean/root/user/$id"
    },
    "/$locale/apps/derivean/root/user/$id/view": {
      "filePath": "$locale/apps/derivean/root/user/$id/view.tsx",
      "parent": "/$locale/apps/derivean/root/user/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/$id/conflicts": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/$id/conflicts.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/$id/dependencies": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/$id/dependencies.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/$id/production": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/$id/production.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/$id/requirements": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/$id/requirements.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/$id/view": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/$id/view.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/production/$id": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/production/$id.tsx",
      "parent": "/$locale/apps/derivean/game/management",
      "children": [
        "/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies",
        "/$locale/apps/derivean/game/management/blueprint/production/$id/requirements",
        "/$locale/apps/derivean/game/management/blueprint/production/$id/resources"
      ]
    },
    "/$locale/apps/derivean/root/blueprint/production/$id/dependencies": {
      "filePath": "$locale/apps/derivean/root/blueprint/production/$id/dependencies.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/production/$id"
    },
    "/$locale/apps/derivean/root/blueprint/production/$id/requirements": {
      "filePath": "$locale/apps/derivean/root/blueprint/production/$id/requirements.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/production/$id"
    },
    "/$locale/apps/derivean/root/blueprint/production/$id/resources": {
      "filePath": "$locale/apps/derivean/root/blueprint/production/$id/resources.tsx",
      "parent": "/$locale/apps/derivean/root/blueprint/production/$id"
    },
    "/$locale/apps/derivean/root/user/$id/building/list": {
      "filePath": "$locale/apps/derivean/root/user/$id/building/list.tsx",
      "parent": "/$locale/apps/derivean/root/user/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/production/$id/dependencies": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/production/$id/dependencies.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/production/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/production/$id/requirements": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/production/$id/requirements.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/production/$id"
    },
    "/$locale/apps/derivean/game/management/blueprint/production/$id/resources": {
      "filePath": "$locale/apps/derivean/game/management/blueprint/production/$id/resources.tsx",
      "parent": "/$locale/apps/derivean/game/management/blueprint/production/$id"
    }
  }
}
ROUTE_MANIFEST_END */
