/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './@routes/__root'
import { Route as LocaleImport } from './@routes/$locale'
import { Route as IndexImport } from './@routes/index'
import { Route as LocaleIndexImport } from './@routes/$locale/index'
import { Route as LocaleAppsDeriveanImport } from './@routes/$locale/apps/derivean'
import { Route as LocaleAppsDeriveanRootImport } from './@routes/$locale/apps/derivean/root'
import { Route as LocaleAppsDeriveanGameImport } from './@routes/$locale/apps/derivean/game'
import { Route as LocaleAppsDeriveanGameIndexImport } from './@routes/$locale/apps/derivean/game/index'
import { Route as LocaleAppsDeriveanPublicRegisterImport } from './@routes/$locale/apps/derivean/public/register'
import { Route as LocaleAppsDeriveanPublicLogoutImport } from './@routes/$locale/apps/derivean/public/logout'
import { Route as LocaleAppsDeriveanPublicLoginImport } from './@routes/$locale/apps/derivean/public/login'
import { Route as LocaleAppsDeriveanRootUserIdImport } from './@routes/$locale/apps/derivean/root/user/$id'
import { Route as LocaleAppsDeriveanRootResourceIdImport } from './@routes/$locale/apps/derivean/root/resource/$id'
import { Route as LocaleAppsDeriveanRootBuildingIdImport } from './@routes/$locale/apps/derivean/root/building/$id'
import { Route as LocaleAppsDeriveanRootUserListIndexImport } from './@routes/$locale/apps/derivean/root/user/list/index'
import { Route as LocaleAppsDeriveanRootTagListIndexImport } from './@routes/$locale/apps/derivean/root/tag/list/index'
import { Route as LocaleAppsDeriveanRootResourceListIndexImport } from './@routes/$locale/apps/derivean/root/resource/list/index'
import { Route as LocaleAppsDeriveanRootBuildingListIndexImport } from './@routes/$locale/apps/derivean/root/building/list/index'
import { Route as LocaleAppsDeriveanGameBuildingListIndexImport } from './@routes/$locale/apps/derivean/game/building/list/index'
import { Route as LocaleAppsDeriveanRootBuildingBaseIdImport } from './@routes/$locale/apps/derivean/root/building/base/$id'
import { Route as LocaleAppsDeriveanRootUserIdViewIndexImport } from './@routes/$locale/apps/derivean/root/user/$id/view/index'
import { Route as LocaleAppsDeriveanRootResourceIdViewIndexImport } from './@routes/$locale/apps/derivean/root/resource/$id/view/index'
import { Route as LocaleAppsDeriveanRootBuildingBaseListIndexImport } from './@routes/$locale/apps/derivean/root/building/base/list/index'
import { Route as LocaleAppsDeriveanRootBuildingIdViewIndexImport } from './@routes/$locale/apps/derivean/root/building/$id/view/index'
import { Route as LocaleAppsDeriveanRootUserIdBuildingListIndexImport } from './@routes/$locale/apps/derivean/root/user/$id/building/list/index'
import { Route as LocaleAppsDeriveanRootBuildingBaseIdViewIndexImport } from './@routes/$locale/apps/derivean/root/building/base/$id/view/index'
import { Route as LocaleAppsDeriveanRootBuildingBaseIdEditIndexImport } from './@routes/$locale/apps/derivean/root/building/base/$id/edit/index'
import { Route as LocaleAppsDeriveanRootBuildingIdStorageListIndexImport } from './@routes/$locale/apps/derivean/root/building/$id/storage/list/index'
import { Route as LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexImport } from './@routes/$locale/apps/derivean/root/building/base/$id/storage/list/index'
import { Route as LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexImport } from './@routes/$locale/apps/derivean/root/building/base/$id/requirement/list/index'

// Create/Update Routes

const LocaleRoute = LocaleImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleIndexRoute = LocaleIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleAppsDeriveanRoute = LocaleAppsDeriveanImport.update({
  id: '/apps/derivean',
  path: '/apps/derivean',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleAppsDeriveanRootRoute = LocaleAppsDeriveanRootImport.update({
  id: '/root',
  path: '/root',
  getParentRoute: () => LocaleAppsDeriveanRoute,
} as any)

const LocaleAppsDeriveanGameRoute = LocaleAppsDeriveanGameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => LocaleAppsDeriveanRoute,
} as any)

const LocaleAppsDeriveanGameIndexRoute =
  LocaleAppsDeriveanGameIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAppsDeriveanGameRoute,
  } as any)

const LocaleAppsDeriveanPublicRegisterRoute =
  LocaleAppsDeriveanPublicRegisterImport.update({
    id: '/public/register',
    path: '/public/register',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any)

const LocaleAppsDeriveanPublicLogoutRoute =
  LocaleAppsDeriveanPublicLogoutImport.update({
    id: '/public/logout',
    path: '/public/logout',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any)

const LocaleAppsDeriveanPublicLoginRoute =
  LocaleAppsDeriveanPublicLoginImport.update({
    id: '/public/login',
    path: '/public/login',
    getParentRoute: () => LocaleAppsDeriveanRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdRoute =
  LocaleAppsDeriveanRootUserIdImport.update({
    id: '/user/$id',
    path: '/user/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootResourceIdRoute =
  LocaleAppsDeriveanRootResourceIdImport.update({
    id: '/resource/$id',
    path: '/resource/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingIdRoute =
  LocaleAppsDeriveanRootBuildingIdImport.update({
    id: '/building/$id',
    path: '/building/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootUserListIndexRoute =
  LocaleAppsDeriveanRootUserListIndexImport.update({
    id: '/user/list/',
    path: '/user/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootTagListIndexRoute =
  LocaleAppsDeriveanRootTagListIndexImport.update({
    id: '/tag/list/',
    path: '/tag/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootResourceListIndexRoute =
  LocaleAppsDeriveanRootResourceListIndexImport.update({
    id: '/resource/list/',
    path: '/resource/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingListIndexRoute =
  LocaleAppsDeriveanRootBuildingListIndexImport.update({
    id: '/building/list/',
    path: '/building/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanGameBuildingListIndexRoute =
  LocaleAppsDeriveanGameBuildingListIndexImport.update({
    id: '/building/list/',
    path: '/building/list/',
    getParentRoute: () => LocaleAppsDeriveanGameRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingBaseIdRoute =
  LocaleAppsDeriveanRootBuildingBaseIdImport.update({
    id: '/building/base/$id',
    path: '/building/base/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdViewIndexRoute =
  LocaleAppsDeriveanRootUserIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootUserIdRoute,
  } as any)

const LocaleAppsDeriveanRootResourceIdViewIndexRoute =
  LocaleAppsDeriveanRootResourceIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootResourceIdRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingBaseListIndexRoute =
  LocaleAppsDeriveanRootBuildingBaseListIndexImport.update({
    id: '/building/base/list/',
    path: '/building/base/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingIdViewIndexRoute =
  LocaleAppsDeriveanRootBuildingIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootBuildingIdRoute,
  } as any)

const LocaleAppsDeriveanRootUserIdBuildingListIndexRoute =
  LocaleAppsDeriveanRootUserIdBuildingListIndexImport.update({
    id: '/building/list/',
    path: '/building/list/',
    getParentRoute: () => LocaleAppsDeriveanRootUserIdRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute =
  LocaleAppsDeriveanRootBuildingBaseIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootBuildingBaseIdRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute =
  LocaleAppsDeriveanRootBuildingBaseIdEditIndexImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => LocaleAppsDeriveanRootBuildingBaseIdRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute =
  LocaleAppsDeriveanRootBuildingIdStorageListIndexImport.update({
    id: '/storage/list/',
    path: '/storage/list/',
    getParentRoute: () => LocaleAppsDeriveanRootBuildingIdRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute =
  LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexImport.update({
    id: '/storage/list/',
    path: '/storage/list/',
    getParentRoute: () => LocaleAppsDeriveanRootBuildingBaseIdRoute,
  } as any)

const LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute =
  LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexImport.update({
    id: '/requirement/list/',
    path: '/requirement/list/',
    getParentRoute: () => LocaleAppsDeriveanRootBuildingBaseIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/derivean': {
      id: '/$locale/apps/derivean'
      path: '/apps/derivean'
      fullPath: '/$locale/apps/derivean'
      preLoaderRoute: typeof LocaleAppsDeriveanImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/derivean/game': {
      id: '/$locale/apps/derivean/game'
      path: '/game'
      fullPath: '/$locale/apps/derivean/game'
      preLoaderRoute: typeof LocaleAppsDeriveanGameImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/root': {
      id: '/$locale/apps/derivean/root'
      path: '/root'
      fullPath: '/$locale/apps/derivean/root'
      preLoaderRoute: typeof LocaleAppsDeriveanRootImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/public/login': {
      id: '/$locale/apps/derivean/public/login'
      path: '/public/login'
      fullPath: '/$locale/apps/derivean/public/login'
      preLoaderRoute: typeof LocaleAppsDeriveanPublicLoginImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/public/logout': {
      id: '/$locale/apps/derivean/public/logout'
      path: '/public/logout'
      fullPath: '/$locale/apps/derivean/public/logout'
      preLoaderRoute: typeof LocaleAppsDeriveanPublicLogoutImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/public/register': {
      id: '/$locale/apps/derivean/public/register'
      path: '/public/register'
      fullPath: '/$locale/apps/derivean/public/register'
      preLoaderRoute: typeof LocaleAppsDeriveanPublicRegisterImport
      parentRoute: typeof LocaleAppsDeriveanImport
    }
    '/$locale/apps/derivean/game/': {
      id: '/$locale/apps/derivean/game/'
      path: '/'
      fullPath: '/$locale/apps/derivean/game/'
      preLoaderRoute: typeof LocaleAppsDeriveanGameIndexImport
      parentRoute: typeof LocaleAppsDeriveanGameImport
    }
    '/$locale/apps/derivean/root/building/$id': {
      id: '/$locale/apps/derivean/root/building/$id'
      path: '/building/$id'
      fullPath: '/$locale/apps/derivean/root/building/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/resource/$id': {
      id: '/$locale/apps/derivean/root/resource/$id'
      path: '/resource/$id'
      fullPath: '/$locale/apps/derivean/root/resource/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootResourceIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/user/$id': {
      id: '/$locale/apps/derivean/root/user/$id'
      path: '/user/$id'
      fullPath: '/$locale/apps/derivean/root/user/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/building/base/$id': {
      id: '/$locale/apps/derivean/root/building/base/$id'
      path: '/building/base/$id'
      fullPath: '/$locale/apps/derivean/root/building/base/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/game/building/list/': {
      id: '/$locale/apps/derivean/game/building/list/'
      path: '/building/list'
      fullPath: '/$locale/apps/derivean/game/building/list'
      preLoaderRoute: typeof LocaleAppsDeriveanGameBuildingListIndexImport
      parentRoute: typeof LocaleAppsDeriveanGameImport
    }
    '/$locale/apps/derivean/root/building/list/': {
      id: '/$locale/apps/derivean/root/building/list/'
      path: '/building/list'
      fullPath: '/$locale/apps/derivean/root/building/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/resource/list/': {
      id: '/$locale/apps/derivean/root/resource/list/'
      path: '/resource/list'
      fullPath: '/$locale/apps/derivean/root/resource/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootResourceListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/tag/list/': {
      id: '/$locale/apps/derivean/root/tag/list/'
      path: '/tag/list'
      fullPath: '/$locale/apps/derivean/root/tag/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootTagListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/user/list/': {
      id: '/$locale/apps/derivean/root/user/list/'
      path: '/user/list'
      fullPath: '/$locale/apps/derivean/root/user/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/building/$id/view/': {
      id: '/$locale/apps/derivean/root/building/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/building/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootBuildingIdImport
    }
    '/$locale/apps/derivean/root/building/base/list/': {
      id: '/$locale/apps/derivean/root/building/base/list/'
      path: '/building/base/list'
      fullPath: '/$locale/apps/derivean/root/building/base/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingBaseListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/resource/$id/view/': {
      id: '/$locale/apps/derivean/root/resource/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/resource/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootResourceIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootResourceIdImport
    }
    '/$locale/apps/derivean/root/user/$id/view/': {
      id: '/$locale/apps/derivean/root/user/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/user/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootUserIdImport
    }
    '/$locale/apps/derivean/root/building/$id/storage/list/': {
      id: '/$locale/apps/derivean/root/building/$id/storage/list/'
      path: '/storage/list'
      fullPath: '/$locale/apps/derivean/root/building/$id/storage/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingIdStorageListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootBuildingIdImport
    }
    '/$locale/apps/derivean/root/building/base/$id/edit/': {
      id: '/$locale/apps/derivean/root/building/base/$id/edit/'
      path: '/edit'
      fullPath: '/$locale/apps/derivean/root/building/base/$id/edit'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdEditIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdImport
    }
    '/$locale/apps/derivean/root/building/base/$id/view/': {
      id: '/$locale/apps/derivean/root/building/base/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/building/base/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdImport
    }
    '/$locale/apps/derivean/root/user/$id/building/list/': {
      id: '/$locale/apps/derivean/root/user/$id/building/list/'
      path: '/building/list'
      fullPath: '/$locale/apps/derivean/root/user/$id/building/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootUserIdBuildingListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootUserIdImport
    }
    '/$locale/apps/derivean/root/building/base/$id/requirement/list/': {
      id: '/$locale/apps/derivean/root/building/base/$id/requirement/list/'
      path: '/requirement/list'
      fullPath: '/$locale/apps/derivean/root/building/base/$id/requirement/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdImport
    }
    '/$locale/apps/derivean/root/building/base/$id/storage/list/': {
      id: '/$locale/apps/derivean/root/building/base/$id/storage/list/'
      path: '/storage/list'
      fullPath: '/$locale/apps/derivean/root/building/base/$id/storage/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdImport
    }
  }
}

// Create and export the route tree

interface LocaleAppsDeriveanGameRouteChildren {
  LocaleAppsDeriveanGameIndexRoute: typeof LocaleAppsDeriveanGameIndexRoute
  LocaleAppsDeriveanGameBuildingListIndexRoute: typeof LocaleAppsDeriveanGameBuildingListIndexRoute
}

const LocaleAppsDeriveanGameRouteChildren: LocaleAppsDeriveanGameRouteChildren =
  {
    LocaleAppsDeriveanGameIndexRoute: LocaleAppsDeriveanGameIndexRoute,
    LocaleAppsDeriveanGameBuildingListIndexRoute:
      LocaleAppsDeriveanGameBuildingListIndexRoute,
  }

const LocaleAppsDeriveanGameRouteWithChildren =
  LocaleAppsDeriveanGameRoute._addFileChildren(
    LocaleAppsDeriveanGameRouteChildren,
  )

interface LocaleAppsDeriveanRootBuildingIdRouteChildren {
  LocaleAppsDeriveanRootBuildingIdViewIndexRoute: typeof LocaleAppsDeriveanRootBuildingIdViewIndexRoute
  LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute: typeof LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute
}

const LocaleAppsDeriveanRootBuildingIdRouteChildren: LocaleAppsDeriveanRootBuildingIdRouteChildren =
  {
    LocaleAppsDeriveanRootBuildingIdViewIndexRoute:
      LocaleAppsDeriveanRootBuildingIdViewIndexRoute,
    LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute:
      LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute,
  }

const LocaleAppsDeriveanRootBuildingIdRouteWithChildren =
  LocaleAppsDeriveanRootBuildingIdRoute._addFileChildren(
    LocaleAppsDeriveanRootBuildingIdRouteChildren,
  )

interface LocaleAppsDeriveanRootResourceIdRouteChildren {
  LocaleAppsDeriveanRootResourceIdViewIndexRoute: typeof LocaleAppsDeriveanRootResourceIdViewIndexRoute
}

const LocaleAppsDeriveanRootResourceIdRouteChildren: LocaleAppsDeriveanRootResourceIdRouteChildren =
  {
    LocaleAppsDeriveanRootResourceIdViewIndexRoute:
      LocaleAppsDeriveanRootResourceIdViewIndexRoute,
  }

const LocaleAppsDeriveanRootResourceIdRouteWithChildren =
  LocaleAppsDeriveanRootResourceIdRoute._addFileChildren(
    LocaleAppsDeriveanRootResourceIdRouteChildren,
  )

interface LocaleAppsDeriveanRootUserIdRouteChildren {
  LocaleAppsDeriveanRootUserIdViewIndexRoute: typeof LocaleAppsDeriveanRootUserIdViewIndexRoute
  LocaleAppsDeriveanRootUserIdBuildingListIndexRoute: typeof LocaleAppsDeriveanRootUserIdBuildingListIndexRoute
}

const LocaleAppsDeriveanRootUserIdRouteChildren: LocaleAppsDeriveanRootUserIdRouteChildren =
  {
    LocaleAppsDeriveanRootUserIdViewIndexRoute:
      LocaleAppsDeriveanRootUserIdViewIndexRoute,
    LocaleAppsDeriveanRootUserIdBuildingListIndexRoute:
      LocaleAppsDeriveanRootUserIdBuildingListIndexRoute,
  }

const LocaleAppsDeriveanRootUserIdRouteWithChildren =
  LocaleAppsDeriveanRootUserIdRoute._addFileChildren(
    LocaleAppsDeriveanRootUserIdRouteChildren,
  )

interface LocaleAppsDeriveanRootBuildingBaseIdRouteChildren {
  LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute
  LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute
  LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute
  LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute
}

const LocaleAppsDeriveanRootBuildingBaseIdRouteChildren: LocaleAppsDeriveanRootBuildingBaseIdRouteChildren =
  {
    LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute:
      LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute,
    LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute:
      LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute,
    LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute:
      LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute,
    LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute:
      LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute,
  }

const LocaleAppsDeriveanRootBuildingBaseIdRouteWithChildren =
  LocaleAppsDeriveanRootBuildingBaseIdRoute._addFileChildren(
    LocaleAppsDeriveanRootBuildingBaseIdRouteChildren,
  )

interface LocaleAppsDeriveanRootRouteChildren {
  LocaleAppsDeriveanRootBuildingIdRoute: typeof LocaleAppsDeriveanRootBuildingIdRouteWithChildren
  LocaleAppsDeriveanRootResourceIdRoute: typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  LocaleAppsDeriveanRootUserIdRoute: typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  LocaleAppsDeriveanRootBuildingBaseIdRoute: typeof LocaleAppsDeriveanRootBuildingBaseIdRouteWithChildren
  LocaleAppsDeriveanRootBuildingListIndexRoute: typeof LocaleAppsDeriveanRootBuildingListIndexRoute
  LocaleAppsDeriveanRootResourceListIndexRoute: typeof LocaleAppsDeriveanRootResourceListIndexRoute
  LocaleAppsDeriveanRootTagListIndexRoute: typeof LocaleAppsDeriveanRootTagListIndexRoute
  LocaleAppsDeriveanRootUserListIndexRoute: typeof LocaleAppsDeriveanRootUserListIndexRoute
  LocaleAppsDeriveanRootBuildingBaseListIndexRoute: typeof LocaleAppsDeriveanRootBuildingBaseListIndexRoute
}

const LocaleAppsDeriveanRootRouteChildren: LocaleAppsDeriveanRootRouteChildren =
  {
    LocaleAppsDeriveanRootBuildingIdRoute:
      LocaleAppsDeriveanRootBuildingIdRouteWithChildren,
    LocaleAppsDeriveanRootResourceIdRoute:
      LocaleAppsDeriveanRootResourceIdRouteWithChildren,
    LocaleAppsDeriveanRootUserIdRoute:
      LocaleAppsDeriveanRootUserIdRouteWithChildren,
    LocaleAppsDeriveanRootBuildingBaseIdRoute:
      LocaleAppsDeriveanRootBuildingBaseIdRouteWithChildren,
    LocaleAppsDeriveanRootBuildingListIndexRoute:
      LocaleAppsDeriveanRootBuildingListIndexRoute,
    LocaleAppsDeriveanRootResourceListIndexRoute:
      LocaleAppsDeriveanRootResourceListIndexRoute,
    LocaleAppsDeriveanRootTagListIndexRoute:
      LocaleAppsDeriveanRootTagListIndexRoute,
    LocaleAppsDeriveanRootUserListIndexRoute:
      LocaleAppsDeriveanRootUserListIndexRoute,
    LocaleAppsDeriveanRootBuildingBaseListIndexRoute:
      LocaleAppsDeriveanRootBuildingBaseListIndexRoute,
  }

const LocaleAppsDeriveanRootRouteWithChildren =
  LocaleAppsDeriveanRootRoute._addFileChildren(
    LocaleAppsDeriveanRootRouteChildren,
  )

interface LocaleAppsDeriveanRouteChildren {
  LocaleAppsDeriveanGameRoute: typeof LocaleAppsDeriveanGameRouteWithChildren
  LocaleAppsDeriveanRootRoute: typeof LocaleAppsDeriveanRootRouteWithChildren
  LocaleAppsDeriveanPublicLoginRoute: typeof LocaleAppsDeriveanPublicLoginRoute
  LocaleAppsDeriveanPublicLogoutRoute: typeof LocaleAppsDeriveanPublicLogoutRoute
  LocaleAppsDeriveanPublicRegisterRoute: typeof LocaleAppsDeriveanPublicRegisterRoute
}

const LocaleAppsDeriveanRouteChildren: LocaleAppsDeriveanRouteChildren = {
  LocaleAppsDeriveanGameRoute: LocaleAppsDeriveanGameRouteWithChildren,
  LocaleAppsDeriveanRootRoute: LocaleAppsDeriveanRootRouteWithChildren,
  LocaleAppsDeriveanPublicLoginRoute: LocaleAppsDeriveanPublicLoginRoute,
  LocaleAppsDeriveanPublicLogoutRoute: LocaleAppsDeriveanPublicLogoutRoute,
  LocaleAppsDeriveanPublicRegisterRoute: LocaleAppsDeriveanPublicRegisterRoute,
}

const LocaleAppsDeriveanRouteWithChildren =
  LocaleAppsDeriveanRoute._addFileChildren(LocaleAppsDeriveanRouteChildren)

interface LocaleRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAppsDeriveanRoute: typeof LocaleAppsDeriveanRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAppsDeriveanRoute: LocaleAppsDeriveanRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanRouteWithChildren
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean/public/login': typeof LocaleAppsDeriveanPublicLoginRoute
  '/$locale/apps/derivean/public/logout': typeof LocaleAppsDeriveanPublicLogoutRoute
  '/$locale/apps/derivean/public/register': typeof LocaleAppsDeriveanPublicRegisterRoute
  '/$locale/apps/derivean/game/': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/building/$id': typeof LocaleAppsDeriveanRootBuildingIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/$id': typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  '/$locale/apps/derivean/root/user/$id': typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  '/$locale/apps/derivean/root/building/base/$id': typeof LocaleAppsDeriveanRootBuildingBaseIdRouteWithChildren
  '/$locale/apps/derivean/game/building/list': typeof LocaleAppsDeriveanGameBuildingListIndexRoute
  '/$locale/apps/derivean/root/building/list': typeof LocaleAppsDeriveanRootBuildingListIndexRoute
  '/$locale/apps/derivean/root/resource/list': typeof LocaleAppsDeriveanRootResourceListIndexRoute
  '/$locale/apps/derivean/root/tag/list': typeof LocaleAppsDeriveanRootTagListIndexRoute
  '/$locale/apps/derivean/root/user/list': typeof LocaleAppsDeriveanRootUserListIndexRoute
  '/$locale/apps/derivean/root/building/$id/view': typeof LocaleAppsDeriveanRootBuildingIdViewIndexRoute
  '/$locale/apps/derivean/root/building/base/list': typeof LocaleAppsDeriveanRootBuildingBaseListIndexRoute
  '/$locale/apps/derivean/root/resource/$id/view': typeof LocaleAppsDeriveanRootResourceIdViewIndexRoute
  '/$locale/apps/derivean/root/user/$id/view': typeof LocaleAppsDeriveanRootUserIdViewIndexRoute
  '/$locale/apps/derivean/root/building/$id/storage/list': typeof LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/edit': typeof LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/view': typeof LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute
  '/$locale/apps/derivean/root/user/$id/building/list': typeof LocaleAppsDeriveanRootUserIdBuildingListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/requirement/list': typeof LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/storage/list': typeof LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean/public/login': typeof LocaleAppsDeriveanPublicLoginRoute
  '/$locale/apps/derivean/public/logout': typeof LocaleAppsDeriveanPublicLogoutRoute
  '/$locale/apps/derivean/public/register': typeof LocaleAppsDeriveanPublicRegisterRoute
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/building/$id': typeof LocaleAppsDeriveanRootBuildingIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/$id': typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  '/$locale/apps/derivean/root/user/$id': typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  '/$locale/apps/derivean/root/building/base/$id': typeof LocaleAppsDeriveanRootBuildingBaseIdRouteWithChildren
  '/$locale/apps/derivean/game/building/list': typeof LocaleAppsDeriveanGameBuildingListIndexRoute
  '/$locale/apps/derivean/root/building/list': typeof LocaleAppsDeriveanRootBuildingListIndexRoute
  '/$locale/apps/derivean/root/resource/list': typeof LocaleAppsDeriveanRootResourceListIndexRoute
  '/$locale/apps/derivean/root/tag/list': typeof LocaleAppsDeriveanRootTagListIndexRoute
  '/$locale/apps/derivean/root/user/list': typeof LocaleAppsDeriveanRootUserListIndexRoute
  '/$locale/apps/derivean/root/building/$id/view': typeof LocaleAppsDeriveanRootBuildingIdViewIndexRoute
  '/$locale/apps/derivean/root/building/base/list': typeof LocaleAppsDeriveanRootBuildingBaseListIndexRoute
  '/$locale/apps/derivean/root/resource/$id/view': typeof LocaleAppsDeriveanRootResourceIdViewIndexRoute
  '/$locale/apps/derivean/root/user/$id/view': typeof LocaleAppsDeriveanRootUserIdViewIndexRoute
  '/$locale/apps/derivean/root/building/$id/storage/list': typeof LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/edit': typeof LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/view': typeof LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute
  '/$locale/apps/derivean/root/user/$id/building/list': typeof LocaleAppsDeriveanRootUserIdBuildingListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/requirement/list': typeof LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/storage/list': typeof LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanRouteWithChildren
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean/public/login': typeof LocaleAppsDeriveanPublicLoginRoute
  '/$locale/apps/derivean/public/logout': typeof LocaleAppsDeriveanPublicLogoutRoute
  '/$locale/apps/derivean/public/register': typeof LocaleAppsDeriveanPublicRegisterRoute
  '/$locale/apps/derivean/game/': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/building/$id': typeof LocaleAppsDeriveanRootBuildingIdRouteWithChildren
  '/$locale/apps/derivean/root/resource/$id': typeof LocaleAppsDeriveanRootResourceIdRouteWithChildren
  '/$locale/apps/derivean/root/user/$id': typeof LocaleAppsDeriveanRootUserIdRouteWithChildren
  '/$locale/apps/derivean/root/building/base/$id': typeof LocaleAppsDeriveanRootBuildingBaseIdRouteWithChildren
  '/$locale/apps/derivean/game/building/list/': typeof LocaleAppsDeriveanGameBuildingListIndexRoute
  '/$locale/apps/derivean/root/building/list/': typeof LocaleAppsDeriveanRootBuildingListIndexRoute
  '/$locale/apps/derivean/root/resource/list/': typeof LocaleAppsDeriveanRootResourceListIndexRoute
  '/$locale/apps/derivean/root/tag/list/': typeof LocaleAppsDeriveanRootTagListIndexRoute
  '/$locale/apps/derivean/root/user/list/': typeof LocaleAppsDeriveanRootUserListIndexRoute
  '/$locale/apps/derivean/root/building/$id/view/': typeof LocaleAppsDeriveanRootBuildingIdViewIndexRoute
  '/$locale/apps/derivean/root/building/base/list/': typeof LocaleAppsDeriveanRootBuildingBaseListIndexRoute
  '/$locale/apps/derivean/root/resource/$id/view/': typeof LocaleAppsDeriveanRootResourceIdViewIndexRoute
  '/$locale/apps/derivean/root/user/$id/view/': typeof LocaleAppsDeriveanRootUserIdViewIndexRoute
  '/$locale/apps/derivean/root/building/$id/storage/list/': typeof LocaleAppsDeriveanRootBuildingIdStorageListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/edit/': typeof LocaleAppsDeriveanRootBuildingBaseIdEditIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/view/': typeof LocaleAppsDeriveanRootBuildingBaseIdViewIndexRoute
  '/$locale/apps/derivean/root/user/$id/building/list/': typeof LocaleAppsDeriveanRootUserIdBuildingListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/requirement/list/': typeof LocaleAppsDeriveanRootBuildingBaseIdRequirementListIndexRoute
  '/$locale/apps/derivean/root/building/base/$id/storage/list/': typeof LocaleAppsDeriveanRootBuildingBaseIdStorageListIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/apps/derivean'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/public/login'
    | '/$locale/apps/derivean/public/logout'
    | '/$locale/apps/derivean/public/register'
    | '/$locale/apps/derivean/game/'
    | '/$locale/apps/derivean/root/building/$id'
    | '/$locale/apps/derivean/root/resource/$id'
    | '/$locale/apps/derivean/root/user/$id'
    | '/$locale/apps/derivean/root/building/base/$id'
    | '/$locale/apps/derivean/game/building/list'
    | '/$locale/apps/derivean/root/building/list'
    | '/$locale/apps/derivean/root/resource/list'
    | '/$locale/apps/derivean/root/tag/list'
    | '/$locale/apps/derivean/root/user/list'
    | '/$locale/apps/derivean/root/building/$id/view'
    | '/$locale/apps/derivean/root/building/base/list'
    | '/$locale/apps/derivean/root/resource/$id/view'
    | '/$locale/apps/derivean/root/user/$id/view'
    | '/$locale/apps/derivean/root/building/$id/storage/list'
    | '/$locale/apps/derivean/root/building/base/$id/edit'
    | '/$locale/apps/derivean/root/building/base/$id/view'
    | '/$locale/apps/derivean/root/user/$id/building/list'
    | '/$locale/apps/derivean/root/building/base/$id/requirement/list'
    | '/$locale/apps/derivean/root/building/base/$id/storage/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/apps/derivean'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/public/login'
    | '/$locale/apps/derivean/public/logout'
    | '/$locale/apps/derivean/public/register'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root/building/$id'
    | '/$locale/apps/derivean/root/resource/$id'
    | '/$locale/apps/derivean/root/user/$id'
    | '/$locale/apps/derivean/root/building/base/$id'
    | '/$locale/apps/derivean/game/building/list'
    | '/$locale/apps/derivean/root/building/list'
    | '/$locale/apps/derivean/root/resource/list'
    | '/$locale/apps/derivean/root/tag/list'
    | '/$locale/apps/derivean/root/user/list'
    | '/$locale/apps/derivean/root/building/$id/view'
    | '/$locale/apps/derivean/root/building/base/list'
    | '/$locale/apps/derivean/root/resource/$id/view'
    | '/$locale/apps/derivean/root/user/$id/view'
    | '/$locale/apps/derivean/root/building/$id/storage/list'
    | '/$locale/apps/derivean/root/building/base/$id/edit'
    | '/$locale/apps/derivean/root/building/base/$id/view'
    | '/$locale/apps/derivean/root/user/$id/building/list'
    | '/$locale/apps/derivean/root/building/base/$id/requirement/list'
    | '/$locale/apps/derivean/root/building/base/$id/storage/list'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/apps/derivean'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/public/login'
    | '/$locale/apps/derivean/public/logout'
    | '/$locale/apps/derivean/public/register'
    | '/$locale/apps/derivean/game/'
    | '/$locale/apps/derivean/root/building/$id'
    | '/$locale/apps/derivean/root/resource/$id'
    | '/$locale/apps/derivean/root/user/$id'
    | '/$locale/apps/derivean/root/building/base/$id'
    | '/$locale/apps/derivean/game/building/list/'
    | '/$locale/apps/derivean/root/building/list/'
    | '/$locale/apps/derivean/root/resource/list/'
    | '/$locale/apps/derivean/root/tag/list/'
    | '/$locale/apps/derivean/root/user/list/'
    | '/$locale/apps/derivean/root/building/$id/view/'
    | '/$locale/apps/derivean/root/building/base/list/'
    | '/$locale/apps/derivean/root/resource/$id/view/'
    | '/$locale/apps/derivean/root/user/$id/view/'
    | '/$locale/apps/derivean/root/building/$id/storage/list/'
    | '/$locale/apps/derivean/root/building/base/$id/edit/'
    | '/$locale/apps/derivean/root/building/base/$id/view/'
    | '/$locale/apps/derivean/root/user/$id/building/list/'
    | '/$locale/apps/derivean/root/building/base/$id/requirement/list/'
    | '/$locale/apps/derivean/root/building/base/$id/storage/list/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale": {
      "filePath": "$locale.tsx",
      "children": [
        "/$locale/",
        "/$locale/apps/derivean"
      ]
    },
    "/$locale/": {
      "filePath": "$locale/index.tsx",
      "parent": "/$locale"
    },
    "/$locale/apps/derivean": {
      "filePath": "$locale/apps/derivean.tsx",
      "parent": "/$locale",
      "children": [
        "/$locale/apps/derivean/game",
        "/$locale/apps/derivean/root",
        "/$locale/apps/derivean/public/login",
        "/$locale/apps/derivean/public/logout",
        "/$locale/apps/derivean/public/register"
      ]
    },
    "/$locale/apps/derivean/game": {
      "filePath": "$locale/apps/derivean/game.tsx",
      "parent": "/$locale/apps/derivean",
      "children": [
        "/$locale/apps/derivean/game/",
        "/$locale/apps/derivean/game/building/list/"
      ]
    },
    "/$locale/apps/derivean/root": {
      "filePath": "$locale/apps/derivean/root.tsx",
      "parent": "/$locale/apps/derivean",
      "children": [
        "/$locale/apps/derivean/root/building/$id",
        "/$locale/apps/derivean/root/resource/$id",
        "/$locale/apps/derivean/root/user/$id",
        "/$locale/apps/derivean/root/building/base/$id",
        "/$locale/apps/derivean/root/building/list/",
        "/$locale/apps/derivean/root/resource/list/",
        "/$locale/apps/derivean/root/tag/list/",
        "/$locale/apps/derivean/root/user/list/",
        "/$locale/apps/derivean/root/building/base/list/"
      ]
    },
    "/$locale/apps/derivean/public/login": {
      "filePath": "$locale/apps/derivean/public/login.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/public/logout": {
      "filePath": "$locale/apps/derivean/public/logout.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/public/register": {
      "filePath": "$locale/apps/derivean/public/register.tsx",
      "parent": "/$locale/apps/derivean"
    },
    "/$locale/apps/derivean/game/": {
      "filePath": "$locale/apps/derivean/game/index.tsx",
      "parent": "/$locale/apps/derivean/game"
    },
    "/$locale/apps/derivean/root/building/$id": {
      "filePath": "$locale/apps/derivean/root/building/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/building/$id/view/",
        "/$locale/apps/derivean/root/building/$id/storage/list/"
      ]
    },
    "/$locale/apps/derivean/root/resource/$id": {
      "filePath": "$locale/apps/derivean/root/resource/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/resource/$id/view/"
      ]
    },
    "/$locale/apps/derivean/root/user/$id": {
      "filePath": "$locale/apps/derivean/root/user/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/user/$id/view/",
        "/$locale/apps/derivean/root/user/$id/building/list/"
      ]
    },
    "/$locale/apps/derivean/root/building/base/$id": {
      "filePath": "$locale/apps/derivean/root/building/base/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/building/base/$id/edit/",
        "/$locale/apps/derivean/root/building/base/$id/view/",
        "/$locale/apps/derivean/root/building/base/$id/requirement/list/",
        "/$locale/apps/derivean/root/building/base/$id/storage/list/"
      ]
    },
    "/$locale/apps/derivean/game/building/list/": {
      "filePath": "$locale/apps/derivean/game/building/list/index.tsx",
      "parent": "/$locale/apps/derivean/game"
    },
    "/$locale/apps/derivean/root/building/list/": {
      "filePath": "$locale/apps/derivean/root/building/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/resource/list/": {
      "filePath": "$locale/apps/derivean/root/resource/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/tag/list/": {
      "filePath": "$locale/apps/derivean/root/tag/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/user/list/": {
      "filePath": "$locale/apps/derivean/root/user/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/building/$id/view/": {
      "filePath": "$locale/apps/derivean/root/building/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/building/$id"
    },
    "/$locale/apps/derivean/root/building/base/list/": {
      "filePath": "$locale/apps/derivean/root/building/base/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/resource/$id/view/": {
      "filePath": "$locale/apps/derivean/root/resource/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/resource/$id"
    },
    "/$locale/apps/derivean/root/user/$id/view/": {
      "filePath": "$locale/apps/derivean/root/user/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/user/$id"
    },
    "/$locale/apps/derivean/root/building/$id/storage/list/": {
      "filePath": "$locale/apps/derivean/root/building/$id/storage/list/index.tsx",
      "parent": "/$locale/apps/derivean/root/building/$id"
    },
    "/$locale/apps/derivean/root/building/base/$id/edit/": {
      "filePath": "$locale/apps/derivean/root/building/base/$id/edit/index.tsx",
      "parent": "/$locale/apps/derivean/root/building/base/$id"
    },
    "/$locale/apps/derivean/root/building/base/$id/view/": {
      "filePath": "$locale/apps/derivean/root/building/base/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/building/base/$id"
    },
    "/$locale/apps/derivean/root/user/$id/building/list/": {
      "filePath": "$locale/apps/derivean/root/user/$id/building/list/index.tsx",
      "parent": "/$locale/apps/derivean/root/user/$id"
    },
    "/$locale/apps/derivean/root/building/base/$id/requirement/list/": {
      "filePath": "$locale/apps/derivean/root/building/base/$id/requirement/list/index.tsx",
      "parent": "/$locale/apps/derivean/root/building/base/$id"
    },
    "/$locale/apps/derivean/root/building/base/$id/storage/list/": {
      "filePath": "$locale/apps/derivean/root/building/base/$id/storage/list/index.tsx",
      "parent": "/$locale/apps/derivean/root/building/base/$id"
    }
  }
}
ROUTE_MANIFEST_END */
