/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './@routes/__root'
import { Route as AboutImport } from './@routes/about'
import { Route as LocaleImport } from './@routes/$locale'
import { Route as IndexImport } from './@routes/index'
import { Route as LocaleAppsImport } from './@routes/$locale/apps'
import { Route as LocalePublicIndexImport } from './@routes/$locale/public/index'
import { Route as LocaleAppsIndexImport } from './@routes/$locale/apps/index'
import { Route as LocalePublicRegisterImport } from './@routes/$locale/public/register'
import { Route as LocalePublicLogoutImport } from './@routes/$locale/public/logout'
import { Route as LocalePublicLoginImport } from './@routes/$locale/public/login'
import { Route as LocaleAppsPlaygroundImport } from './@routes/$locale/apps/playground'
import { Route as LocaleAppsPlaygroundIndexImport } from './@routes/$locale/apps/playground/index'
import { Route as LocaleAppsMonyeIndexImport } from './@routes/$locale/apps/monye/index'
import { Route as LocaleAppsDeriveanIndexImport } from './@routes/$locale/apps/derivean/index'
import { Route as LocaleAppsDeriveanRootImport } from './@routes/$locale/apps/derivean/root'
import { Route as LocaleAppsDeriveanGameImport } from './@routes/$locale/apps/derivean/game'
import { Route as LocaleAppsDeriveanGameIndexImport } from './@routes/$locale/apps/derivean/game/index'
import { Route as LocaleAppsDeriveanRootSlotIdImport } from './@routes/$locale/apps/derivean/root/slot/$id'
import { Route as LocaleAppsDeriveanRootItemIdImport } from './@routes/$locale/apps/derivean/root/item/$id'
import { Route as LocaleAppsDeriveanRootInventoryIdImport } from './@routes/$locale/apps/derivean/root/inventory/$id'
import { Route as LocaleAppsDeriveanRootSlotListIndexImport } from './@routes/$locale/apps/derivean/root/slot/list/index'
import { Route as LocaleAppsDeriveanRootItemListIndexImport } from './@routes/$locale/apps/derivean/root/item/list/index'
import { Route as LocaleAppsDeriveanRootInventoryListIndexImport } from './@routes/$locale/apps/derivean/root/inventory/list/index'
import { Route as LocaleAppsDeriveanRootSlotIdViewIndexImport } from './@routes/$locale/apps/derivean/root/slot/$id/view/index'
import { Route as LocaleAppsDeriveanRootItemIdViewIndexImport } from './@routes/$locale/apps/derivean/root/item/$id/view/index'
import { Route as LocaleAppsDeriveanRootInventoryIdViewIndexImport } from './@routes/$locale/apps/derivean/root/inventory/$id/view/index'
import { Route as LocaleAppsDeriveanRootInventoryIdSlotListIndexImport } from './@routes/$locale/apps/derivean/root/inventory/$id/slot/list/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LocaleRoute = LocaleImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAppsRoute = LocaleAppsImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => LocaleRoute,
} as any)

const LocalePublicIndexRoute = LocalePublicIndexImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleAppsIndexRoute = LocaleAppsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppsRoute,
} as any)

const LocalePublicRegisterRoute = LocalePublicRegisterImport.update({
  id: '/public/register',
  path: '/public/register',
  getParentRoute: () => LocaleRoute,
} as any)

const LocalePublicLogoutRoute = LocalePublicLogoutImport.update({
  id: '/public/logout',
  path: '/public/logout',
  getParentRoute: () => LocaleRoute,
} as any)

const LocalePublicLoginRoute = LocalePublicLoginImport.update({
  id: '/public/login',
  path: '/public/login',
  getParentRoute: () => LocaleRoute,
} as any)

const LocaleAppsPlaygroundRoute = LocaleAppsPlaygroundImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LocaleAppsRoute,
} as any)

const LocaleAppsPlaygroundIndexRoute = LocaleAppsPlaygroundIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppsPlaygroundRoute,
} as any)

const LocaleAppsMonyeIndexRoute = LocaleAppsMonyeIndexImport.update({
  id: '/monye/',
  path: '/monye/',
  getParentRoute: () => LocaleAppsRoute,
} as any)

const LocaleAppsDeriveanIndexRoute = LocaleAppsDeriveanIndexImport.update({
  id: '/derivean/',
  path: '/derivean/',
  getParentRoute: () => LocaleAppsRoute,
} as any)

const LocaleAppsDeriveanRootRoute = LocaleAppsDeriveanRootImport.update({
  id: '/derivean/root',
  path: '/derivean/root',
  getParentRoute: () => LocaleAppsRoute,
} as any)

const LocaleAppsDeriveanGameRoute = LocaleAppsDeriveanGameImport.update({
  id: '/derivean/game',
  path: '/derivean/game',
  getParentRoute: () => LocaleAppsRoute,
} as any)

const LocaleAppsDeriveanGameIndexRoute =
  LocaleAppsDeriveanGameIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAppsDeriveanGameRoute,
  } as any)

const LocaleAppsDeriveanRootSlotIdRoute =
  LocaleAppsDeriveanRootSlotIdImport.update({
    id: '/slot/$id',
    path: '/slot/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootItemIdRoute =
  LocaleAppsDeriveanRootItemIdImport.update({
    id: '/item/$id',
    path: '/item/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootInventoryIdRoute =
  LocaleAppsDeriveanRootInventoryIdImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootSlotListIndexRoute =
  LocaleAppsDeriveanRootSlotListIndexImport.update({
    id: '/slot/list/',
    path: '/slot/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootItemListIndexRoute =
  LocaleAppsDeriveanRootItemListIndexImport.update({
    id: '/item/list/',
    path: '/item/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootInventoryListIndexRoute =
  LocaleAppsDeriveanRootInventoryListIndexImport.update({
    id: '/inventory/list/',
    path: '/inventory/list/',
    getParentRoute: () => LocaleAppsDeriveanRootRoute,
  } as any)

const LocaleAppsDeriveanRootSlotIdViewIndexRoute =
  LocaleAppsDeriveanRootSlotIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootSlotIdRoute,
  } as any)

const LocaleAppsDeriveanRootItemIdViewIndexRoute =
  LocaleAppsDeriveanRootItemIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootItemIdRoute,
  } as any)

const LocaleAppsDeriveanRootInventoryIdViewIndexRoute =
  LocaleAppsDeriveanRootInventoryIdViewIndexImport.update({
    id: '/view/',
    path: '/view/',
    getParentRoute: () => LocaleAppsDeriveanRootInventoryIdRoute,
  } as any)

const LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute =
  LocaleAppsDeriveanRootInventoryIdSlotListIndexImport.update({
    id: '/slot/list/',
    path: '/slot/list/',
    getParentRoute: () => LocaleAppsDeriveanRootInventoryIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/$locale/apps': {
      id: '/$locale/apps'
      path: '/apps'
      fullPath: '/$locale/apps'
      preLoaderRoute: typeof LocaleAppsImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/playground': {
      id: '/$locale/apps/playground'
      path: '/playground'
      fullPath: '/$locale/apps/playground'
      preLoaderRoute: typeof LocaleAppsPlaygroundImport
      parentRoute: typeof LocaleAppsImport
    }
    '/$locale/public/login': {
      id: '/$locale/public/login'
      path: '/public/login'
      fullPath: '/$locale/public/login'
      preLoaderRoute: typeof LocalePublicLoginImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/public/logout': {
      id: '/$locale/public/logout'
      path: '/public/logout'
      fullPath: '/$locale/public/logout'
      preLoaderRoute: typeof LocalePublicLogoutImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/public/register': {
      id: '/$locale/public/register'
      path: '/public/register'
      fullPath: '/$locale/public/register'
      preLoaderRoute: typeof LocalePublicRegisterImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/': {
      id: '/$locale/apps/'
      path: '/'
      fullPath: '/$locale/apps/'
      preLoaderRoute: typeof LocaleAppsIndexImport
      parentRoute: typeof LocaleAppsImport
    }
    '/$locale/public/': {
      id: '/$locale/public/'
      path: '/public'
      fullPath: '/$locale/public'
      preLoaderRoute: typeof LocalePublicIndexImport
      parentRoute: typeof LocaleImport
    }
    '/$locale/apps/derivean/game': {
      id: '/$locale/apps/derivean/game'
      path: '/derivean/game'
      fullPath: '/$locale/apps/derivean/game'
      preLoaderRoute: typeof LocaleAppsDeriveanGameImport
      parentRoute: typeof LocaleAppsImport
    }
    '/$locale/apps/derivean/root': {
      id: '/$locale/apps/derivean/root'
      path: '/derivean/root'
      fullPath: '/$locale/apps/derivean/root'
      preLoaderRoute: typeof LocaleAppsDeriveanRootImport
      parentRoute: typeof LocaleAppsImport
    }
    '/$locale/apps/derivean/': {
      id: '/$locale/apps/derivean/'
      path: '/derivean'
      fullPath: '/$locale/apps/derivean'
      preLoaderRoute: typeof LocaleAppsDeriveanIndexImport
      parentRoute: typeof LocaleAppsImport
    }
    '/$locale/apps/monye/': {
      id: '/$locale/apps/monye/'
      path: '/monye'
      fullPath: '/$locale/apps/monye'
      preLoaderRoute: typeof LocaleAppsMonyeIndexImport
      parentRoute: typeof LocaleAppsImport
    }
    '/$locale/apps/playground/': {
      id: '/$locale/apps/playground/'
      path: '/'
      fullPath: '/$locale/apps/playground/'
      preLoaderRoute: typeof LocaleAppsPlaygroundIndexImport
      parentRoute: typeof LocaleAppsPlaygroundImport
    }
    '/$locale/apps/derivean/game/': {
      id: '/$locale/apps/derivean/game/'
      path: '/'
      fullPath: '/$locale/apps/derivean/game/'
      preLoaderRoute: typeof LocaleAppsDeriveanGameIndexImport
      parentRoute: typeof LocaleAppsDeriveanGameImport
    }
    '/$locale/apps/derivean/root/inventory/$id': {
      id: '/$locale/apps/derivean/root/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/$locale/apps/derivean/root/inventory/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootInventoryIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/item/$id': {
      id: '/$locale/apps/derivean/root/item/$id'
      path: '/item/$id'
      fullPath: '/$locale/apps/derivean/root/item/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootItemIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/slot/$id': {
      id: '/$locale/apps/derivean/root/slot/$id'
      path: '/slot/$id'
      fullPath: '/$locale/apps/derivean/root/slot/$id'
      preLoaderRoute: typeof LocaleAppsDeriveanRootSlotIdImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/inventory/list/': {
      id: '/$locale/apps/derivean/root/inventory/list/'
      path: '/inventory/list'
      fullPath: '/$locale/apps/derivean/root/inventory/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootInventoryListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/item/list/': {
      id: '/$locale/apps/derivean/root/item/list/'
      path: '/item/list'
      fullPath: '/$locale/apps/derivean/root/item/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootItemListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/slot/list/': {
      id: '/$locale/apps/derivean/root/slot/list/'
      path: '/slot/list'
      fullPath: '/$locale/apps/derivean/root/slot/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootSlotListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootImport
    }
    '/$locale/apps/derivean/root/inventory/$id/view/': {
      id: '/$locale/apps/derivean/root/inventory/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/inventory/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootInventoryIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootInventoryIdImport
    }
    '/$locale/apps/derivean/root/item/$id/view/': {
      id: '/$locale/apps/derivean/root/item/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/item/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootItemIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootItemIdImport
    }
    '/$locale/apps/derivean/root/slot/$id/view/': {
      id: '/$locale/apps/derivean/root/slot/$id/view/'
      path: '/view'
      fullPath: '/$locale/apps/derivean/root/slot/$id/view'
      preLoaderRoute: typeof LocaleAppsDeriveanRootSlotIdViewIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootSlotIdImport
    }
    '/$locale/apps/derivean/root/inventory/$id/slot/list/': {
      id: '/$locale/apps/derivean/root/inventory/$id/slot/list/'
      path: '/slot/list'
      fullPath: '/$locale/apps/derivean/root/inventory/$id/slot/list'
      preLoaderRoute: typeof LocaleAppsDeriveanRootInventoryIdSlotListIndexImport
      parentRoute: typeof LocaleAppsDeriveanRootInventoryIdImport
    }
  }
}

// Create and export the route tree

interface LocaleAppsPlaygroundRouteChildren {
  LocaleAppsPlaygroundIndexRoute: typeof LocaleAppsPlaygroundIndexRoute
}

const LocaleAppsPlaygroundRouteChildren: LocaleAppsPlaygroundRouteChildren = {
  LocaleAppsPlaygroundIndexRoute: LocaleAppsPlaygroundIndexRoute,
}

const LocaleAppsPlaygroundRouteWithChildren =
  LocaleAppsPlaygroundRoute._addFileChildren(LocaleAppsPlaygroundRouteChildren)

interface LocaleAppsDeriveanGameRouteChildren {
  LocaleAppsDeriveanGameIndexRoute: typeof LocaleAppsDeriveanGameIndexRoute
}

const LocaleAppsDeriveanGameRouteChildren: LocaleAppsDeriveanGameRouteChildren =
  {
    LocaleAppsDeriveanGameIndexRoute: LocaleAppsDeriveanGameIndexRoute,
  }

const LocaleAppsDeriveanGameRouteWithChildren =
  LocaleAppsDeriveanGameRoute._addFileChildren(
    LocaleAppsDeriveanGameRouteChildren,
  )

interface LocaleAppsDeriveanRootInventoryIdRouteChildren {
  LocaleAppsDeriveanRootInventoryIdViewIndexRoute: typeof LocaleAppsDeriveanRootInventoryIdViewIndexRoute
  LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute: typeof LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute
}

const LocaleAppsDeriveanRootInventoryIdRouteChildren: LocaleAppsDeriveanRootInventoryIdRouteChildren =
  {
    LocaleAppsDeriveanRootInventoryIdViewIndexRoute:
      LocaleAppsDeriveanRootInventoryIdViewIndexRoute,
    LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute:
      LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute,
  }

const LocaleAppsDeriveanRootInventoryIdRouteWithChildren =
  LocaleAppsDeriveanRootInventoryIdRoute._addFileChildren(
    LocaleAppsDeriveanRootInventoryIdRouteChildren,
  )

interface LocaleAppsDeriveanRootItemIdRouteChildren {
  LocaleAppsDeriveanRootItemIdViewIndexRoute: typeof LocaleAppsDeriveanRootItemIdViewIndexRoute
}

const LocaleAppsDeriveanRootItemIdRouteChildren: LocaleAppsDeriveanRootItemIdRouteChildren =
  {
    LocaleAppsDeriveanRootItemIdViewIndexRoute:
      LocaleAppsDeriveanRootItemIdViewIndexRoute,
  }

const LocaleAppsDeriveanRootItemIdRouteWithChildren =
  LocaleAppsDeriveanRootItemIdRoute._addFileChildren(
    LocaleAppsDeriveanRootItemIdRouteChildren,
  )

interface LocaleAppsDeriveanRootSlotIdRouteChildren {
  LocaleAppsDeriveanRootSlotIdViewIndexRoute: typeof LocaleAppsDeriveanRootSlotIdViewIndexRoute
}

const LocaleAppsDeriveanRootSlotIdRouteChildren: LocaleAppsDeriveanRootSlotIdRouteChildren =
  {
    LocaleAppsDeriveanRootSlotIdViewIndexRoute:
      LocaleAppsDeriveanRootSlotIdViewIndexRoute,
  }

const LocaleAppsDeriveanRootSlotIdRouteWithChildren =
  LocaleAppsDeriveanRootSlotIdRoute._addFileChildren(
    LocaleAppsDeriveanRootSlotIdRouteChildren,
  )

interface LocaleAppsDeriveanRootRouteChildren {
  LocaleAppsDeriveanRootInventoryIdRoute: typeof LocaleAppsDeriveanRootInventoryIdRouteWithChildren
  LocaleAppsDeriveanRootItemIdRoute: typeof LocaleAppsDeriveanRootItemIdRouteWithChildren
  LocaleAppsDeriveanRootSlotIdRoute: typeof LocaleAppsDeriveanRootSlotIdRouteWithChildren
  LocaleAppsDeriveanRootInventoryListIndexRoute: typeof LocaleAppsDeriveanRootInventoryListIndexRoute
  LocaleAppsDeriveanRootItemListIndexRoute: typeof LocaleAppsDeriveanRootItemListIndexRoute
  LocaleAppsDeriveanRootSlotListIndexRoute: typeof LocaleAppsDeriveanRootSlotListIndexRoute
}

const LocaleAppsDeriveanRootRouteChildren: LocaleAppsDeriveanRootRouteChildren =
  {
    LocaleAppsDeriveanRootInventoryIdRoute:
      LocaleAppsDeriveanRootInventoryIdRouteWithChildren,
    LocaleAppsDeriveanRootItemIdRoute:
      LocaleAppsDeriveanRootItemIdRouteWithChildren,
    LocaleAppsDeriveanRootSlotIdRoute:
      LocaleAppsDeriveanRootSlotIdRouteWithChildren,
    LocaleAppsDeriveanRootInventoryListIndexRoute:
      LocaleAppsDeriveanRootInventoryListIndexRoute,
    LocaleAppsDeriveanRootItemListIndexRoute:
      LocaleAppsDeriveanRootItemListIndexRoute,
    LocaleAppsDeriveanRootSlotListIndexRoute:
      LocaleAppsDeriveanRootSlotListIndexRoute,
  }

const LocaleAppsDeriveanRootRouteWithChildren =
  LocaleAppsDeriveanRootRoute._addFileChildren(
    LocaleAppsDeriveanRootRouteChildren,
  )

interface LocaleAppsRouteChildren {
  LocaleAppsPlaygroundRoute: typeof LocaleAppsPlaygroundRouteWithChildren
  LocaleAppsIndexRoute: typeof LocaleAppsIndexRoute
  LocaleAppsDeriveanGameRoute: typeof LocaleAppsDeriveanGameRouteWithChildren
  LocaleAppsDeriveanRootRoute: typeof LocaleAppsDeriveanRootRouteWithChildren
  LocaleAppsDeriveanIndexRoute: typeof LocaleAppsDeriveanIndexRoute
  LocaleAppsMonyeIndexRoute: typeof LocaleAppsMonyeIndexRoute
}

const LocaleAppsRouteChildren: LocaleAppsRouteChildren = {
  LocaleAppsPlaygroundRoute: LocaleAppsPlaygroundRouteWithChildren,
  LocaleAppsIndexRoute: LocaleAppsIndexRoute,
  LocaleAppsDeriveanGameRoute: LocaleAppsDeriveanGameRouteWithChildren,
  LocaleAppsDeriveanRootRoute: LocaleAppsDeriveanRootRouteWithChildren,
  LocaleAppsDeriveanIndexRoute: LocaleAppsDeriveanIndexRoute,
  LocaleAppsMonyeIndexRoute: LocaleAppsMonyeIndexRoute,
}

const LocaleAppsRouteWithChildren = LocaleAppsRoute._addFileChildren(
  LocaleAppsRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAppsRoute: typeof LocaleAppsRouteWithChildren
  LocalePublicLoginRoute: typeof LocalePublicLoginRoute
  LocalePublicLogoutRoute: typeof LocalePublicLogoutRoute
  LocalePublicRegisterRoute: typeof LocalePublicRegisterRoute
  LocalePublicIndexRoute: typeof LocalePublicIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAppsRoute: LocaleAppsRouteWithChildren,
  LocalePublicLoginRoute: LocalePublicLoginRoute,
  LocalePublicLogoutRoute: LocalePublicLogoutRoute,
  LocalePublicRegisterRoute: LocalePublicRegisterRoute,
  LocalePublicIndexRoute: LocalePublicIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/$locale/apps': typeof LocaleAppsRouteWithChildren
  '/$locale/apps/playground': typeof LocaleAppsPlaygroundRouteWithChildren
  '/$locale/public/login': typeof LocalePublicLoginRoute
  '/$locale/public/logout': typeof LocalePublicLogoutRoute
  '/$locale/public/register': typeof LocalePublicRegisterRoute
  '/$locale/apps/': typeof LocaleAppsIndexRoute
  '/$locale/public': typeof LocalePublicIndexRoute
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanIndexRoute
  '/$locale/apps/monye': typeof LocaleAppsMonyeIndexRoute
  '/$locale/apps/playground/': typeof LocaleAppsPlaygroundIndexRoute
  '/$locale/apps/derivean/game/': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/inventory/$id': typeof LocaleAppsDeriveanRootInventoryIdRouteWithChildren
  '/$locale/apps/derivean/root/item/$id': typeof LocaleAppsDeriveanRootItemIdRouteWithChildren
  '/$locale/apps/derivean/root/slot/$id': typeof LocaleAppsDeriveanRootSlotIdRouteWithChildren
  '/$locale/apps/derivean/root/inventory/list': typeof LocaleAppsDeriveanRootInventoryListIndexRoute
  '/$locale/apps/derivean/root/item/list': typeof LocaleAppsDeriveanRootItemListIndexRoute
  '/$locale/apps/derivean/root/slot/list': typeof LocaleAppsDeriveanRootSlotListIndexRoute
  '/$locale/apps/derivean/root/inventory/$id/view': typeof LocaleAppsDeriveanRootInventoryIdViewIndexRoute
  '/$locale/apps/derivean/root/item/$id/view': typeof LocaleAppsDeriveanRootItemIdViewIndexRoute
  '/$locale/apps/derivean/root/slot/$id/view': typeof LocaleAppsDeriveanRootSlotIdViewIndexRoute
  '/$locale/apps/derivean/root/inventory/$id/slot/list': typeof LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/$locale/public/login': typeof LocalePublicLoginRoute
  '/$locale/public/logout': typeof LocalePublicLogoutRoute
  '/$locale/public/register': typeof LocalePublicRegisterRoute
  '/$locale/apps': typeof LocaleAppsIndexRoute
  '/$locale/public': typeof LocalePublicIndexRoute
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean': typeof LocaleAppsDeriveanIndexRoute
  '/$locale/apps/monye': typeof LocaleAppsMonyeIndexRoute
  '/$locale/apps/playground': typeof LocaleAppsPlaygroundIndexRoute
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/inventory/$id': typeof LocaleAppsDeriveanRootInventoryIdRouteWithChildren
  '/$locale/apps/derivean/root/item/$id': typeof LocaleAppsDeriveanRootItemIdRouteWithChildren
  '/$locale/apps/derivean/root/slot/$id': typeof LocaleAppsDeriveanRootSlotIdRouteWithChildren
  '/$locale/apps/derivean/root/inventory/list': typeof LocaleAppsDeriveanRootInventoryListIndexRoute
  '/$locale/apps/derivean/root/item/list': typeof LocaleAppsDeriveanRootItemListIndexRoute
  '/$locale/apps/derivean/root/slot/list': typeof LocaleAppsDeriveanRootSlotListIndexRoute
  '/$locale/apps/derivean/root/inventory/$id/view': typeof LocaleAppsDeriveanRootInventoryIdViewIndexRoute
  '/$locale/apps/derivean/root/item/$id/view': typeof LocaleAppsDeriveanRootItemIdViewIndexRoute
  '/$locale/apps/derivean/root/slot/$id/view': typeof LocaleAppsDeriveanRootSlotIdViewIndexRoute
  '/$locale/apps/derivean/root/inventory/$id/slot/list': typeof LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/$locale/apps': typeof LocaleAppsRouteWithChildren
  '/$locale/apps/playground': typeof LocaleAppsPlaygroundRouteWithChildren
  '/$locale/public/login': typeof LocalePublicLoginRoute
  '/$locale/public/logout': typeof LocalePublicLogoutRoute
  '/$locale/public/register': typeof LocalePublicRegisterRoute
  '/$locale/apps/': typeof LocaleAppsIndexRoute
  '/$locale/public/': typeof LocalePublicIndexRoute
  '/$locale/apps/derivean/game': typeof LocaleAppsDeriveanGameRouteWithChildren
  '/$locale/apps/derivean/root': typeof LocaleAppsDeriveanRootRouteWithChildren
  '/$locale/apps/derivean/': typeof LocaleAppsDeriveanIndexRoute
  '/$locale/apps/monye/': typeof LocaleAppsMonyeIndexRoute
  '/$locale/apps/playground/': typeof LocaleAppsPlaygroundIndexRoute
  '/$locale/apps/derivean/game/': typeof LocaleAppsDeriveanGameIndexRoute
  '/$locale/apps/derivean/root/inventory/$id': typeof LocaleAppsDeriveanRootInventoryIdRouteWithChildren
  '/$locale/apps/derivean/root/item/$id': typeof LocaleAppsDeriveanRootItemIdRouteWithChildren
  '/$locale/apps/derivean/root/slot/$id': typeof LocaleAppsDeriveanRootSlotIdRouteWithChildren
  '/$locale/apps/derivean/root/inventory/list/': typeof LocaleAppsDeriveanRootInventoryListIndexRoute
  '/$locale/apps/derivean/root/item/list/': typeof LocaleAppsDeriveanRootItemListIndexRoute
  '/$locale/apps/derivean/root/slot/list/': typeof LocaleAppsDeriveanRootSlotListIndexRoute
  '/$locale/apps/derivean/root/inventory/$id/view/': typeof LocaleAppsDeriveanRootInventoryIdViewIndexRoute
  '/$locale/apps/derivean/root/item/$id/view/': typeof LocaleAppsDeriveanRootItemIdViewIndexRoute
  '/$locale/apps/derivean/root/slot/$id/view/': typeof LocaleAppsDeriveanRootSlotIdViewIndexRoute
  '/$locale/apps/derivean/root/inventory/$id/slot/list/': typeof LocaleAppsDeriveanRootInventoryIdSlotListIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/$locale/apps'
    | '/$locale/apps/playground'
    | '/$locale/public/login'
    | '/$locale/public/logout'
    | '/$locale/public/register'
    | '/$locale/apps/'
    | '/$locale/public'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean'
    | '/$locale/apps/monye'
    | '/$locale/apps/playground/'
    | '/$locale/apps/derivean/game/'
    | '/$locale/apps/derivean/root/inventory/$id'
    | '/$locale/apps/derivean/root/item/$id'
    | '/$locale/apps/derivean/root/slot/$id'
    | '/$locale/apps/derivean/root/inventory/list'
    | '/$locale/apps/derivean/root/item/list'
    | '/$locale/apps/derivean/root/slot/list'
    | '/$locale/apps/derivean/root/inventory/$id/view'
    | '/$locale/apps/derivean/root/item/$id/view'
    | '/$locale/apps/derivean/root/slot/$id/view'
    | '/$locale/apps/derivean/root/inventory/$id/slot/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/about'
    | '/$locale/public/login'
    | '/$locale/public/logout'
    | '/$locale/public/register'
    | '/$locale/apps'
    | '/$locale/public'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean'
    | '/$locale/apps/monye'
    | '/$locale/apps/playground'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root/inventory/$id'
    | '/$locale/apps/derivean/root/item/$id'
    | '/$locale/apps/derivean/root/slot/$id'
    | '/$locale/apps/derivean/root/inventory/list'
    | '/$locale/apps/derivean/root/item/list'
    | '/$locale/apps/derivean/root/slot/list'
    | '/$locale/apps/derivean/root/inventory/$id/view'
    | '/$locale/apps/derivean/root/item/$id/view'
    | '/$locale/apps/derivean/root/slot/$id/view'
    | '/$locale/apps/derivean/root/inventory/$id/slot/list'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/$locale/apps'
    | '/$locale/apps/playground'
    | '/$locale/public/login'
    | '/$locale/public/logout'
    | '/$locale/public/register'
    | '/$locale/apps/'
    | '/$locale/public/'
    | '/$locale/apps/derivean/game'
    | '/$locale/apps/derivean/root'
    | '/$locale/apps/derivean/'
    | '/$locale/apps/monye/'
    | '/$locale/apps/playground/'
    | '/$locale/apps/derivean/game/'
    | '/$locale/apps/derivean/root/inventory/$id'
    | '/$locale/apps/derivean/root/item/$id'
    | '/$locale/apps/derivean/root/slot/$id'
    | '/$locale/apps/derivean/root/inventory/list/'
    | '/$locale/apps/derivean/root/item/list/'
    | '/$locale/apps/derivean/root/slot/list/'
    | '/$locale/apps/derivean/root/inventory/$id/view/'
    | '/$locale/apps/derivean/root/item/$id/view/'
    | '/$locale/apps/derivean/root/slot/$id/view/'
    | '/$locale/apps/derivean/root/inventory/$id/slot/list/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale": {
      "filePath": "$locale.tsx",
      "children": [
        "/$locale/apps",
        "/$locale/public/login",
        "/$locale/public/logout",
        "/$locale/public/register",
        "/$locale/public/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/$locale/apps": {
      "filePath": "$locale/apps.tsx",
      "parent": "/$locale",
      "children": [
        "/$locale/apps/playground",
        "/$locale/apps/",
        "/$locale/apps/derivean/game",
        "/$locale/apps/derivean/root",
        "/$locale/apps/derivean/",
        "/$locale/apps/monye/"
      ]
    },
    "/$locale/apps/playground": {
      "filePath": "$locale/apps/playground.tsx",
      "parent": "/$locale/apps",
      "children": [
        "/$locale/apps/playground/"
      ]
    },
    "/$locale/public/login": {
      "filePath": "$locale/public/login.tsx",
      "parent": "/$locale"
    },
    "/$locale/public/logout": {
      "filePath": "$locale/public/logout.tsx",
      "parent": "/$locale"
    },
    "/$locale/public/register": {
      "filePath": "$locale/public/register.tsx",
      "parent": "/$locale"
    },
    "/$locale/apps/": {
      "filePath": "$locale/apps/index.tsx",
      "parent": "/$locale/apps"
    },
    "/$locale/public/": {
      "filePath": "$locale/public/index.tsx",
      "parent": "/$locale"
    },
    "/$locale/apps/derivean/game": {
      "filePath": "$locale/apps/derivean/game.tsx",
      "parent": "/$locale/apps",
      "children": [
        "/$locale/apps/derivean/game/"
      ]
    },
    "/$locale/apps/derivean/root": {
      "filePath": "$locale/apps/derivean/root.tsx",
      "parent": "/$locale/apps",
      "children": [
        "/$locale/apps/derivean/root/inventory/$id",
        "/$locale/apps/derivean/root/item/$id",
        "/$locale/apps/derivean/root/slot/$id",
        "/$locale/apps/derivean/root/inventory/list/",
        "/$locale/apps/derivean/root/item/list/",
        "/$locale/apps/derivean/root/slot/list/"
      ]
    },
    "/$locale/apps/derivean/": {
      "filePath": "$locale/apps/derivean/index.tsx",
      "parent": "/$locale/apps"
    },
    "/$locale/apps/monye/": {
      "filePath": "$locale/apps/monye/index.tsx",
      "parent": "/$locale/apps"
    },
    "/$locale/apps/playground/": {
      "filePath": "$locale/apps/playground/index.tsx",
      "parent": "/$locale/apps/playground"
    },
    "/$locale/apps/derivean/game/": {
      "filePath": "$locale/apps/derivean/game/index.tsx",
      "parent": "/$locale/apps/derivean/game"
    },
    "/$locale/apps/derivean/root/inventory/$id": {
      "filePath": "$locale/apps/derivean/root/inventory/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/inventory/$id/view/",
        "/$locale/apps/derivean/root/inventory/$id/slot/list/"
      ]
    },
    "/$locale/apps/derivean/root/item/$id": {
      "filePath": "$locale/apps/derivean/root/item/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/item/$id/view/"
      ]
    },
    "/$locale/apps/derivean/root/slot/$id": {
      "filePath": "$locale/apps/derivean/root/slot/$id.tsx",
      "parent": "/$locale/apps/derivean/root",
      "children": [
        "/$locale/apps/derivean/root/slot/$id/view/"
      ]
    },
    "/$locale/apps/derivean/root/inventory/list/": {
      "filePath": "$locale/apps/derivean/root/inventory/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/item/list/": {
      "filePath": "$locale/apps/derivean/root/item/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/slot/list/": {
      "filePath": "$locale/apps/derivean/root/slot/list/index.tsx",
      "parent": "/$locale/apps/derivean/root"
    },
    "/$locale/apps/derivean/root/inventory/$id/view/": {
      "filePath": "$locale/apps/derivean/root/inventory/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/inventory/$id"
    },
    "/$locale/apps/derivean/root/item/$id/view/": {
      "filePath": "$locale/apps/derivean/root/item/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/item/$id"
    },
    "/$locale/apps/derivean/root/slot/$id/view/": {
      "filePath": "$locale/apps/derivean/root/slot/$id/view/index.tsx",
      "parent": "/$locale/apps/derivean/root/slot/$id"
    },
    "/$locale/apps/derivean/root/inventory/$id/slot/list/": {
      "filePath": "$locale/apps/derivean/root/inventory/$id/slot/list/index.tsx",
      "parent": "/$locale/apps/derivean/root/inventory/$id"
    }
  }
}
ROUTE_MANIFEST_END */
